### ISSUE TITLE
Unsealing a secret using encoded data in a stringData will not work

### ISSUE THREAD

**Issue by FaresKi** [bitnami-labs/sealed-secrets#1038]
**Which component**:
kubeseal version: v0.19.1 

**Describe the bug**
When sealing a secret using `stringData`, if one of the keys happens to be (intentionally) encoded, the unsealing will fail with this error message:  `ErrUnsealFailed - Failed to unseal: illegal base64 data at input byte 4852` (in my case it was 4852).

Here's the controller logs:
```
2022/10/22 14:29:18 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"oc", Name:"secrets", UID:"16e9d938-1f2e-44bb-b2aa-4e7bac884ec7", 
APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"140016", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: illegal base64 data at input byte 4852
```

**To Reproduce**

1. Create a generic secret & use stringData
2. Encode a value you'd like to keep encoded
3. Seal your secret and apply it
4. See error when sealed-controller tries to unseal it.

**Expected behavior**
I expected it to unseal correctly.

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:47:25Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:27:13Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**
I managed to solve the issue using classic data (so, encoding all values, including the already-encoded one).

**Comment by agarcia-oss** [comment]
Hi @FaresKi we're going to proceed to close this ticket since it has not been updated in the last months. Please, try again using our latest controller release in case you want to reproduce the issue.

**Comment by aledeulo** [comment]
Hi, I'm facing a similar issue, but this time with the v0.22.0.
I'm using this manifest as secret base `yaml`:  
```
apiVersion: v1
kind: Secret
metadata:
 name: mongo-test
 namespace: test
type: Opaque
stringData:
    config.properties: |-
        MONGO_USERNAME=username
        MONGO_PASSWORD=c29tZXBhc3N3b3JkaGVyZQo=
```

I'm sealing the manifest to generate the sealed-secret to deploy:
```
cat mongo-secret.yaml | kubeseal --kubeconfig config.yaml --controller-namespace test  --format yaml > mongo-secret-sealed.yaml
```

I'm receiving this sealed yaml file:
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-test
  namespace: test
spec:
  encryptedData:
    config.properties: AgB1+5UaANGVU2UrtfPSLizvEGl0+raLXTYUrRuDs8xZuAkVdCQHhgNpR7BUFar9AFn1jnCRtDGNhsWOqy8m/Yryd4AO1SSiy4aJmqxFxu7ejlbXJpOjsqZ98pU/LwSM2QRNXH1TTuhj53W15/aP7/5XfczN28RJIGCJw3LcSwu8zO1ig8sIVasPXfQHshJTbm/3U6xa3P3mc4YJ6tEPwwcAV4vt/ayIpm/kOhrqmQhMkpouMiwTKPNXCPF/v6oQkkPC7d+XQCc0w+mKDUuITWzWetarIaM8iF9v/kT520FrDZpHBZ2UDIKDMs2NIGVVo9vJoSKDRHAMlYZdTmhuuXWOA9wLQvLPk96UV1GOj9YbofjQK5f5gNyAxWn22uR6DraXg0NlG3kZWzxLfpf4lE3f0nfFBnGeBLM0Dv4SH2R2wmmNwHyGaMl1crzbpcLZ5bb/eotrrsKTC0hoPDa2F4sd0BwuASSCfhaxOdUF/KHJEDvqBex8ZnJD9ANdyeSLRK1hl4dkcE7tPTQco4YMdOjXTpVP24MBrVFdAx4himjyhoqpvGUtjZ6lEAb0MGfdzm+17Rzhbk7W39/HeGURbnXpqJOk7vN2A2OpX2gI4MU7bFq73qhbzO4BYTnqxU8UVRd2NBBg4G/VFVb1RHQMLjRxtGHV2D5AIS12o8CGJ7X7UyYlDT6STVa9xecHqSc28DkKTKpJDZfB9SHlVKNHUHWmNiISEFrVjJCwpVweVEjN01NebyPhAb1/pkiirIQDkon5W+wJmJHICB97gU6jzQY=
  template:
    metadata:
      creationTimestamp: null
      name: mongo-test
      namespace: test
    type: Opaque
```

Create the secret:
```
kubectl apply -f mongo-secret-sealed.yaml
```

Then, when I fetch the created secret, the controller is not properly decoding the `encryptedData` to what was before. See the created secret below:
```
$ kubectl get secret mongo-test -n test -oyaml
apiVersion: v1
data:
  config.properties: TU9OR09fVVNFUk5BTUU9dXNlcm5hbWUKTU9OR09fUEFTU1dPUkQ9YzI5dFpYQmhjM04zYjNKa2FHVnlaUW89
kind: Secret
metadata:
  name: mongo-test
  namespace: sealed-test
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: mongo-test
...
type: Opaque
```
Am I doing something wrong here or this is not supported yet?
Thanks
