### ISSUE TITLE
PodSecurity violation

### ISSUE THREAD

**Issue by jas01** [bitnami-labs/sealed-secrets#1105]
**Which component**:
controller

**Describe the bug**
On a fresh install of OKD 4.12, (kub version 1.25.4) I got this warning when install (with `kustomize build|kubectl create -f -`)  
```
Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "sealed-secrets-controller" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "sealed-secrets-controller" must set securityContext.capabilities.drop=["ALL"]), seccompProfile (pod or container "sealed-secrets-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```
But the controler seem to working, after all it's just a warning.

**Version of Kubernetes**:

- Output of `kubectl version`:
```
Client Version: 4.12.0-0.okd-2023-01-21-055900
Kustomize Version: v4.5.7
Server Version: 4.12.0-0.okd-2023-01-21-055900
Kubernetes Version: v1.25.0-2653+a34b9e9499e6c3-dirty
```

**Additional context**
Not 100% sure it's a bug or because I'm newbie. Any way don't find any reference through google so I create this issue because my OKD just be installed and nothing configured currently, so I'm guessing I would not the only person with this message

**Comment by agarcia-oss** [comment]
Thanks for reporting, @jas01 What's the Sealed Secrets controller version you are using?

**Comment by jas01** [comment]
Sorry....I forgot...
So the version is the last one: 0.19.4
I'm using this url inside my kustomize.yaml :  https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.19.4/controller.yaml

**Comment by alemorcuq** [comment]
Hi, @jas01!

The warning is telling you which settings need to be set up to fix it:

```
- container "sealed-secrets-controller" must set securityContext.allowPrivilegeEscalation=false
- container "sealed-secrets-controller" must set securityContext.capabilities.drop=["ALL"]
- pod or container "sealed-secrets-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost"
```

In our Helm chart it is possible to configure this using the `containerSecurityContext` and `podSecurityContext` parameters in the `values.yaml`.

Since you are using Kustomize, you will need to use it to customize the yaml you are deploying. In the `controller.yaml` file you linked, this block has the settings for the container security context:

```
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
```

And this other block has the settings for the pod security context:

```
      securityContext:
        fsGroup: 65534
```

**Comment by jas01** [comment]
Hi, @alemorcuq 

Thanks a lots. 
It's working well. 
For someone like me, here the bloc for kustomize : 
```yaml
patches:
  - patch: |-
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
```
