### ISSUE TITLE
When sealing multiple secrets in singe yaml file only first is sealed

### ISSUE THREAD

**Issue by elmariofredo** [bitnami-labs/sealed-secrets#114]
Steps to reproduce

```
10:27:56 in ~/Downloads/kubeseal-test
➜ kubectl create secret generic mysecret --dry-run --from-literal=foo=bar -o yaml >mysecret.yaml

10:28:13 in ~/Downloads/kubeseal-test
➜ cat mysecret.yaml                                                                             
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret

10:28:14 in ~/Downloads/kubeseal-test
➜ echo "---" >> mysecret.yaml

10:28:34 in ~/Downloads/kubeseal-test
➜ kubectl create secret generic mysecret2 --dry-run --from-literal=foo2=bar2 -o yaml >>mysecret.yaml

10:28:56 in ~/Downloads/kubeseal-test
➜ cat mysecret.yaml                                                                       
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret
---
apiVersion: v1
data:
  foo2: YmFyMg==
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret2

10:28:59 in ~/Downloads/kubeseal-test
➜ kubeseal --format yaml <mysecret.yaml >mysealedsecret.yaml

10:29:36 in ~/Downloads/kubeseal-test
➜ cat mysealedsecret.yaml 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgBcOSwLF/cCWmAR7J3mZvFBJIYq7QIjBUQbymqHAhhUDwqpukiCRnA3Rr9iTOXUDOQLthjoujU9NLIM/5xpSFy2AjFRexA02B4ZoxqDFD2ZNxh1kFzedKEDRYgt855jaCwZZbqCnJc4Q4I9m0fWioj9+Ij3rFouVlu+QATpqyAZ7baiVa3wYp6s9YnDSsGwS0OI2URfB5wxZyEIF/vmw/TuZe6dN/qgPVQOK3wWN1+/j9dMYFPgUbTi9gcYr7SerYFCwi5dergNLagEb/zovMhQXymvvhFTeqk4AOZXXSpVbUNIIpdatLWntIXa1k7xNWIl+O1y0KHmLEmW8Ynv2GHbl0c04suJTAapMmWcVorlN1eRjmPaXogtPDTrbDMzs4SqFM6KAxhairwpjZEX8A7dIfWohGVb01aD4wjdzWd0Jgi5WL6LyCkhvV7YUGDfoJsV8Av1WF1snRJRh2ChoTGbHre2i6eZXAUUDDsLLnVRvEioCFMsKVe+pkXHwZhDhVrCmdswUB4mvNDolpEDZ/pj0ykz9M6WMTErs9VlNB1OHvWBr/B6AIDU/HTomJ4zd9siMhwN+zksLz88pfF8kcKlC/nHd+3xtsPsL8jZbppp8Bw1DwXu19FGOwpwDyGoFxkeB3OH5ECK9yuhHGdecoPoDLDco4An+NOgLI52Qp9fscTuezA4aw9AH7L71XQzqd6BB9A=
```

you can see only `mysecret` and `mysecret2` is truncated

**Comment by anguslees** [comment]
Yep, the input is assumed to only be a single document, not a full YAML stream atm.  We can change that, but obviously that would only work for `-o yaml` (not json), which unfortunately breaks the symmetry beween these options :(

Related: I think we should completely rethink `kubeseal` to work on individual key values rather than entire Secrets, now that we've changed the SealedSecrets schema.  So we might end up obsoleting this particular issue rather than fixing it directly...

**Comment by elmariofredo** [comment]
@anguslees yes! that would solve another issue we have. We want to allow developers to exchange encrypted credentials so other side get sealed credentials and all they have to do is deploy them to k8s with sealed-secrets setup. Unfortunately currently encrypting side has to know into which namespace it will be deployed as namespace is part of encryption algorithm. So definitely 👍 

Also it would be great to have simple go api to allow integrate sealed-secrets into other tools like helm without need to use whole kubeseal binary and bash magic.

Is there any public roadmap?

Thanks!

**Comment by mkmik** [comment]
What if we use the  `{"apiVersion": "v1", "kind": "List", "items": [...]}` to render to and from json?

**Comment by mkmik** [comment]
FTR, per-item encryption has been implemented in [v0.7.0](https://github.com/bitnami-labs/sealed-secrets/releases/tag/v0.7.0)

**Comment by mkmik** [comment]
> Unfortunately currently encrypting side has to know into which namespace it will be deployed as namespace is part of encryption algorithm. 

This is by design in order to allow you to enforce strict namespace isolation with RBAC rules.
For your use case to work you need to explicitly pass the `sealedsecrets.bitnami.com/cluster-wide: "true"` annotation, see [v0.6.0 release notes](https://github.com/bitnami-labs/sealed-secrets/blob/master/RELEASE-NOTES.md#v060)

**Comment by SerialVelocity** [comment]
It looks like just outputting multiple json objects back-to-back also works:
https://github.com/kubernetes/kubernetes/issues/8362

So you can have:
```
{
  "apiVersion": "v1",
  ...
}
{
  "apiVersion": "v1",
  ...
}
```

I also want it for yaml since it is pretty common to store multiple secrets in one file.

**Comment by voor** [comment]
Outputting multiple json objects doesn't seem to work anymore, getting the following error:
```
error: couldn't get version/kind; json parse error: invalid character '{' after top-level value
```

With:
```
$ kubeseal --version
kubeseal version: v0.12.1+dirty
$ kubectl version --client     
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

```

Example:
```
apiVersion: v1
kind: Secret
metadata:
  name: firstsecret
  namespace: randomns
type: Opaque
stringData:
  SECRET: EXAMPLE
---
apiVersion: v1
kind: Secret
metadata:
  name: secondsecret
  namespace: randomns
type: Opaque
stringData:
  SECRET2: EXAMPLE
```

```
kubectl create -f example.yaml --dry-run=client -o json | kubeseal --cert ../workload-secrets.pem -o yaml
```

**Comment by mkmik** [comment]
A v1/List will work

**Comment by voor** [comment]
Different error, but still an error:
```
error: converting (v1.List) to (v1.Secret): ObjectMeta not present in src
```
```
$ <example.yaml kubeseal --cert workload-secrets.pem -o yaml
```
example.yaml:
```
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: firstsecret
    namespace: randomns
  type: Opaque
  stringData:
    SECRET: EXAMPLE
- apiVersion: v1
  kind: Secret
  metadata:
    name: secondsecret
    namespace: randomns
  type: Opaque
  stringData:
    SECRET2: EXAMPLE
```

Guessing it might have to do with the usage of `stringData`

**Comment by mkmik** [comment]
I meant, it "will" work once implemented

**Comment by voor** [comment]
![](https://media1.giphy.com/media/dBqxeBhK2wzeYOZPfq/giphy.gif?cid=ecf05e47b9d2db5ff722d8137394047dc7c5e78e44a56199&rid=giphy.gif)

**Comment by mkmik** [comment]
It should be easy to implement hence the "good first issue" label. I like small self-contained PRs to review :-)

**Comment by SerialVelocity** [comment]
@voor I meant `kubectl` accepts multiple json without a list being needed, not `kubeseal`

**Comment by mikkosivulainen** [comment]
supporting multiple secrets would be very useful, that way kustomize could be used to create the secrets.

`kubectl create --dry-run=client -k . | kubeseal ...`

**Comment by mkmik** [comment]
once implementing this, let's make sure it works also on `--validate`  (see #474)

**Comment by uncvrd** [comment]
I'm using `kustomize` to generate secrets to send in to the `kubeseal` command. Does anyone have any bash script workarounds to iterate over each secret in a multiyaml output to send to `kubeseal` yet?

I'm very much an amateur at bash scripting so creating a loop that iterates over each secret in a single file (split by `---`??) has been quite difficult for me. 

For example, here's my `yaml`:

```
data:
  firebase-dev-credentials.json: |
    MY_BASE_64_CREDENTIALS
kind: Secret
metadata:
  name: nodejs-firebase-credentials-989t6dg7m2
type: Opaque
---
apiVersion: v1
data:
  AGENDA_DATABASE_URL: |
    MY_BASE_64_URL
kind: Secret
metadata:
  name: nodejs-secrets-c229fkh579
type: Opaque
```

Running `kubectl kustomize .` will output the above text to the shell. How can I loop over each yaml using a bash script to pipe to `kubeseal` in the mean time? Would love any guidance!
