### ISSUE TITLE
Generated secret contains entries from both `template.data` and `encryptedData`

### ISSUE THREAD

**Issue by n9** [bitnami-labs/sealed-secrets#1197]
**Which component**:
controller

**Describe the bug**

Generated secret contains entries from both `template.data` and `encryptedData`.

**To Reproduce**

Create a SealedSecret with `template.data` filled.

**Expected behavior**

I expect that if the template for data is specified, the data of the generated secret will contain the result from the template.

**Version of Kubernetes**:

any version

**Additional context**

This issue is caused by this statement: https://github.com/bitnami-labs/sealed-secrets/blob/ea747b7b0587a4789b3ff9358449497520a6c059/pkg/apis/sealedsecrets/v1alpha1/sealedsecret_expansion.go#L282

It seems to me that one solution could be to add a condition that will skip this statement if `template.data` is set (not empty).

**Comment by alvneiayu** [comment]
hi @n9 

Could you share with us the Sealed Secrets manifest that you are using, please? We need more information to reproduce this problem and to understand what's going on.

Thanks a lot
Álvaro

**Comment by n9** [comment]
Sure. Example:

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: somename
  namespace: somens
spec:
  encryptedData:
    password: encryptedpassword
  template:
    metadata:
      name: somename
      namespace: somens
    data:
      configfile: 'someuser:{{ index . "password" }}'
```

But the source code is quite simple. There are two places where `secret.Data[key]` is written to:
- `EncryptedData` at line 282
- `Template.Data` at line 297

https://github.com/bitnami-labs/sealed-secrets/blob/ea747b7b0587a4789b3ff9358449497520a6c059/pkg/apis/sealedsecrets/v1alpha1/sealedsecret_expansion.go#L273-L298

Therefore, the generated secret will unexpectedly contain both keys: `password` and `configfile`.
