### ISSUE TITLE
Setup sealer: cannot fetch certificate: error trying to reach service: Address is not allowed (AWS EKS)

### ISSUE THREAD

**Issue by rowi1de** [bitnami-labs/sealed-secrets#1206]
I'm currently facing the following issue when using sealed-secrets + https://github.com/bakito/sealed-secrets-web.
As sealed-secret-web is using sealed-secrets API, maybe you guys have an idea:

```shell
2023/05/09 07:22:56 Connection to sealed secrets with (Namespace: infrastructure / ServiceName: sealed-secrets)
2023/05/09 07:22:56 Setup sealer: cannot fetch certificate: error trying to reach service: Address is not allowed
```

- sealed-secrets 2.8.1
with:
```yaml
 repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
  targetRevision: 2.8.1
  helm:
    values: |-
      ingress:
        enabled: true
        hostname: sealed-secrets.something.com
        pathType: Prefix
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          # name of the secret that contains the user/password definitions
          nginx.ingress.kubernetes.io/auth-secret: sealed-secrets-cert-basic-auth
          # message to display with an appropriate context why the authentication is required
          nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - sealed-secrets-cert'

destination:
  server: 'https://kubernetes.default.svc'
  namespace: infrastructure
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
```

- sealed-secrets-web 3.0.7
```yaml
project: infrastructure
source:
  repoURL: 'https://charts.bakito.net'
  targetRevision: 3.0.*
  helm:
    values: |
      sealedSecrets:
        namespace: infrastructure
        serviceName: sealed-secrets
        # certURL: "http://sealed-secrets.infrastructure.svc.cluster.local:8080/v1/cert.pem" # https://github.com/bitnami-labs/sealed-secrets/issues/1206
      disableLoadSecrets: true
  chart: sealed-secrets-web
destination:
  server: 'https://kubernetes.default.svc'
  namespace: infrastructure
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

```

The namespace & service mentioned in the error exist `Namespace: infrastructure / ServiceName: sealed-secrets`
any hints for further debugging welcome
