### ISSUE TITLE
Operator seems to ignore --all-namespaces=false

### ISSUE THREAD

**Issue by PandaScience** [bitnami-labs/sealed-secrets#1207]
**Which component**:
Controller v0.20.5 via Helm Chart v2.8.2

**Describe the bug**
When passing `--all-namespaces=false` to the operator, it still complains about not being able to list/watch SealedSecret and Secret _at cluster scope_ and (maybe as a consequence?) does not unseal the secrets. 

In my understanding, this flag should prevent exactly these error messages:

```
W0211 13:06:41.926115 1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169: failed to list *v1alpha1.SealedSecret: sealedsecrets.bitnami.com is forbidden: User "system:serviceaccount:development:sealed-secrets-controller" cannot list resource "sealedsecrets" in API group "bitnami.com" at the cluster scope

E0211 13:06:41.926204 1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169: Failed to watch *v1alpha1.SealedSecret: failed to list *v1alpha1.SealedSecret: sealedsecrets.bitnami.com is forbidden: User "system:serviceaccount:development:sealed-secrets-controller" cannot list resource "sealedsecrets" in API group "bitnami.com" at the cluster scope

W0211 13:06:41.926239 1 reflector.go:424] pkg/mod/k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:development:sealed-secrets-controller" cannot list resource "secrets" in API group "" at the cluster scope

E0211 13:06:41.926332 1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.0/tools/cache/reflector.go:169: Failed to watch *v1.Secret: failed to list *v1.Secret: secrets is forbidden: User "system:serviceaccount:development:sealed-secrets-controller" cannot list resource "secrets" in API group "" at the cluster scope
```

We tried to set it as ENV variable as well with the same result. When mistyping the option name the operator complains, so I conclude the option is at least recognized.

I'm aware of the following resources, but still cannot figure out if/what we are doing wrong or if it is due to a bug:

- https://github.com/bitnami-labs/sealed-secrets/issues/324
- https://github.com/bitnami-labs/sealed-secrets/issues/157
- https://github.com/bitnami-labs/sealed-secrets/issues/233

**To Reproduce**
In OpenShift, deploy latest version of official Helm Chart with following values file:
```
namespace: development
fullnameOverride: sealed-secrets-controller

# openshift SCC
podSecurityContext:
  fsGroup:
containerSecurityContext:
  runAsUser:

# service account in restricted environment is created separately since we need to
# attach a role binding instead of clusterrolebinding
serviceAccount:
  create: false
  name: sealed-secrets-controller
rbac:
  # need to disable both since we not even have read access to ClusterRoleBindings
  create: false
  clusterRole: false

# BUG?: for some reason this flag is ignored :/
args:
  - "--all-namespaces"
  - "false"

resources: 
  limits:
    cpu: 150m
    memory: 256Mi
```

**Expected behavior**
The controller should only watch the namespace it was deployed to (since we are also not using `--additional-namespaces`).

**Version of Kubernetes**:

OpenShift Version: 4.11

Output of `oc version`:
```
Client Version: 4.10.0-202209231817.p0.gf832032.assembly.stream-f832032
Kubernetes Version: v1.24.6+5658434
```

**Additional context**

We are given a quite restricted OpenShift environment in form of a single namespace, pre-deployed CRDs and a ClusterRole with appropriate permissions to list, watch, create etc. sealedsecrets objects, that we linked to a ServiceAccount via RoleBinding.

**Comment by kvandenhoute** [comment]
The all-namespaces property still needs permissions to resources in the current namespace.

This can be solved by using the additionalNamespaces property + the rbac.namespacedRoles property (see https://github.com/bitnami-labs/sealed-secrets/pull/1240/)
By adding the following to your values, a Role and Rolebinding should be created for sealed-secrets in the _development_ namespace.
```
fullnameOverride: sealed-secrets-controller
rbac:
  create: true
  clusterRole: false
  namespacedRoles: true

serviceAccount:
  create: false
  name: sealed-secrets-controller
additionalNamespaces:
- development

namespace: development
```

If you are unable to create Roles|Rolebindings, you can template the helm chart using the above values to see the requirements.

**Comment by PandaScience** [comment]
Thank you so much for making this change available! This absolutely fixed our deployment issue.

In case someone else is looking for the requirements on the OpenShift platform: On top of deploying the CRDs, we also asked the cluster admins to create the following ClusterRole:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealedsecrets-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
    apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets
  - verbs:
      - update
    apiGroups:
      - bitnami.com
    resources:
      - sealedsecrets/status
```
