### ISSUE TITLE
pre existing secret not replaced with unsealed content

### ISSUE THREAD

**Issue by dosmanak** [bitnami-labs/sealed-secrets#1314]
**Which component**:
docker.io/bitnami/sealed-secrets-controller:v0.21.0

**Describe the bug**

Secret with empty data values created with annotation: `sealedsecrets.bitnami.com/managed: true` is not replaced with sealed secret decrypted data. The secret is created by helm.

**To Reproduce**

Let helm generate some manifests and ignore plaintext secret definition. Using kustomize add annotation `sealedsecrets.bitnami.com/managed: true` to the empty secret.

Create sealed secret with the correct name, apply it. And secret is not replaced.

Secret removal or sealedsecret operator pod deletion forces secret recreation.

**Expected behavior**

Sealed secret operator watches the secret with `managed: true` annotations and replaces the secret if not synced with sealed counterpart.

**Version of Kubernetes**:

- Output of `kubectl version`: 

```
 kubectl version -o yaml
clientVersion:
  buildDate: "2023-06-14T09:53:42Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-06-19T16:10:31Z"
  compiler: gc
  gitCommit: 25b4e43193bcda6c7328a6d147b1fb73a33f1598
  gitTreeState: clean
  gitVersion: v1.27.3
  goVersion: go1.20.5
  major: "1"
  minor: "27"
  platform: linux/amd64
```

**Additional context**
