### ISSUE TITLE
SealedSecret resources from kubeseal do not conform with the openapi schema in the CRD

### ISSUE THREAD

**Issue by dewe** [bitnami-labs/sealed-secrets#1320]
**Which component**:
kubeseal version: v0.23.1

**Describe the bug**
SealedSecrets from kubeseal contains the field `.spec.template.metadata.creationTimestamp: null`, which is not accepted by the CRD schema when tested with `kubeconform` (https://github.com/yannh/kubeconform).

**To Reproduce**

1. Convert the CRD OpenAPI file to a JSON schema in a local file, as described [here](https://github.com/yannh/kubeconform/tree/v0.6.3#CustomResourceDefinition-CRD-Support):

    ```bash
    $ wget -q https://raw.githubusercontent.com/yannh/kubeconform/master/scripts/openapi2jsonschema.py
    $ python openapi2jsonschema.py https://raw.githubusercontent.com/bitnami-labs/sealed-secrets/release/v0.23.1/helm/sealed-secrets/crds/bitnami.com_sealedsecrets.yaml
    JSON schema written to sealedsecret_v1alpha1.json
    ```

2. Create a sample sealed secret: 

    ```bash
    echo -n bar | kubectl create secret generic mysecret --dry-run=client --from-file=foo=/dev/stdin -o json | kubeseal > mysealedsecret.json
    ```

4. Run the `kubeconform`, checking the schema

    ```bash
   $ kubeconform -schema-location='{{ .ResourceKind }}_{{ .ResourceAPIVersion }}.json' mysealedsecret.json

    mysealedsecret.json - SealedSecret mysecret is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/template/metadata' does not validate with file:///Users/dewe/bitbucket/postnord/eks/tmp/test-schemas/sealedsecret_v1alpha1.json#/properties/spec/properties/template/properties/metadata/additionalProperties: additionalProperties 'creationTimestamp' not allowed
    ```

    In output above you find:  ... properties/spec/properties/template/properties/metadata/additionalProperties: **additionalProperties 'creationTimestamp' not allowed**

**Expected behavior**
CRD OpenAPI schema should accept SealedSecrets created by kubeseal. With previous versions of SealedSecrets, kubeconform did not complain about the resource being invalid. 

**Additional context**
I'd guess it's this change that's the root cause: https://github.com/bitnami-labs/sealed-secrets/commit/ebefedf91530ec6311e9ba863d5265d9beeeb273#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R58

Currently we workaround this problem by adding `-skip SealedSecret` to kubeconform.

**Comment by mvisser-nhb** [comment]
+1 I have the same issue

**Comment by CodeReaper** [comment]
> Currently we workaround this problem by adding `-skip SealedSecret` to kubeconform.

We ran into the same issue, but I wanted to share our workaround in case anyone else could benefit of it. Instead of skipping validation we are opting to sanitize the input with `yq` (this approach could also have some drawbacks).

```sh
<generate or print manifests> | yq 'del(.metadata.creationTimestamp)' | kubeconform <arguments>
```

**Comment by Moglum** [comment]
The root cause why `kubeseal` is adding `metadata.creationTimestamp: null` to every `SealedSecret` is probably this https://github.com/kubernetes/kubernetes/issues/67610 
Which just last week started moving, and there is an open PR with a fix https://github.com/kubernetes/kubernetes/pull/130989

**Comment by wiktor-k** [comment]
> could you check with the kubeseal version (0.32.2), please?

Not the poster but FWIW I've tested this with `kubeseal version: v0.33.1` and it seems to be good (no `creationTimestamp: null`s in sight).

The exact command was:

```sh
echo -n SECRET_VALUE | kubectl create secret generic -n apps TOKEN --dry-run=client --from-file=NAME=/dev/stdin -o json | kubeseal -o yaml
```

and that got me:

```yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: TOKEN
  namespace: apps
spec:
  encryptedData:
    NAME: AgADx6SNBRxLIVYK9qVmQ0bweF+NdOAbD3n7UBl4p+qH+aPzxSoDMxzpApYUJww+g1C2/WA2aCgqngOuM8aJRI/LpbtPbnsToMur7eZPXwSmFCOhCBZj43qchk7PKl8aioY8w6UHtuHJHMvAqMSzkfIEToCga6A6bB1jXOzkwr60VLdBBYEtR1GB4+Z8XLWQbtEe1hiT9nCuHM2ExQ8tf5/MmCeXpSaAR2MUv6CWMyfG6TOqyK2HeCXvPzFb7ORspyqf7AdiPkqW/cgedm7nMFFWyUhWxa+hMQUQy2V8/bO3zXf4+ZeUaAW28MNeCUWAofAL4+GcdOtD/iag2X61uJIMM52lEb5Gl03P061c48LUTFPsQ4fE52obVE7IbKn/CkITA+U+GMBvKdOAY5sz79wUBlV4GlJ3kpTt9wwIsaiQLckMCwcbf1EbqI24KM22gUXN93rw3lF8TAjOWFwTHJJaD9WSKZaBIF1UDT6C9hMoC1dglts8T9SLOzXlLcvlsfRDmjr9E7A/KBqxQ9qV2qEsCobhOxyYzy+5kiQhrdvfZVthvEPPLe47jafAITPeAbU3Fcdyi2C9A00BZuxP+vgOmbqaA4AYGYbkbacpDU6gDstyLe4yMfrEAhywSrbS7FsfduHBwjZ/g/+wiUSvWaYYKKoGD5kdXpiXTUjWB5WqhnYtrpBn8Rz3OJLWpKW52aBrghOKOXPOSDBbTHs=
  template:
    metadata:
      name: TOKEN
      namespace: apps
```
