### ISSUE TITLE
`kubeseal` appends extra document separator `---` when format is YAML

### ISSUE THREAD

**Issue by armingerten** [bitnami-labs/sealed-secrets#1330]
**Which component**:
kubeseal (v0.24.0)

**Describe the bug**
When sealing a secret with `kubeseal`, an extra [YAML document separator](https://yaml.org/spec/1.0/#id2561718) (`---`) is added to the output (since version `v0.24.0`). This causes YAML parsers to fail or parse an extra empty document.

**To Reproduce**

1. Create a simple secret file `secret.yml`
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
stringData:
  foo: bar
```
2. Run `kubeseal --format yaml --secret-file secret.yaml --cert cert.pem`

The resulting YAML document will contain an extra document separator at the end:

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
[..]
spec:
  [..]
  template:
    [..]
    type: Opaque
---
```

**Expected behavior**
The resulting YAML document MAY contain a document separator **before** each document. The resulting YAML document MUST NOT contain a trailing document seperator.

**Additional context**
This was most likely caused by https://github.com/bitnami-labs/sealed-secrets/pull/1304 , specifically https://github.com/bitnami-labs/sealed-secrets/pull/1304/files#diff-92f00e9d744fba4dee224973d289d4a24568a3b50a98996622e5928e86dfca04R409 .

This could be solved by putting the document separator in front of every document (instead of the end).
