### ISSUE TITLE
Correct way to validate the kubeseal tarball with Ansible

### ISSUE THREAD

**Issue by fmunteanu** [bitnami-labs/sealed-secrets#1424]
**Which component**:
kubeseal

**Describe the bug**
I'm trying to validate with Ansible the `kubeseal` signature, what is the correct format to use? None of the checksum types provided by Ansible match the contents of your `.sig` file.

```
- name: Extract tarball
  ansible.builtin.get_url:
    url: https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.5/kubeseal-0.24.5-linux-arm64.tar.gz
    checksum: sha256:https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.5/kubeseal-0.24.5-linux-arm64.tar.gz.sig
    dest: /tmp
    owner: root
    group: root
    mode: '0644'
```

I checked for md5sum, sha1sum, sha224sum, sha256sum, sha384sum and sha512sum. The signature file has the string:
```
MEQCIBov/K3V06TADW+iboEdqaqYIulkkloGhqn/zuBzWj7QAiAoV4iov5zvZcpNAWxr5QRKSE1zU/h4hVsMOjNfKAb3fQ==
```
