### ISSUE TITLE
Ability to enable TLS on Ingress with custom certificate which exists on the cluster already

### ISSUE THREAD

**Issue by yesoos** [bitnami-labs/sealed-secrets#1498]
**Which component**:
sealed-secrets helm chart v2.15.2

**Is your feature request related to a problem? Please describe.**
I would like to use a tls secret for the ingress which already exists on the cluster. For now it's not possible to enable tls if certificate is not generated, provided in helm or generated by cert-manager

**Describe the solution you'd like**
Ability to use a precreated secret with tls certificate or just ability to enable tls and use the default ingress certificate.

**Comment by alemorcuq** [comment]
Hi, @yesoos.

You can provide a custom tls secrets using the `ingress.extraTls` parameter in the chart. For example:

```
ingress:
  enabled: true
  hostname: my-sealed-secrets.local
  tls: true
  extraTls:
  - hosts:
    - my-sealed-secrets.local
    secretName: my-certificate-secret
```
