### ISSUE TITLE
template.metadata.name ignored in sealed secret

### ISSUE THREAD

**Issue by ErikEngerd** [bitnami-labs/sealed-secrets#1543]
**Which component**:
sealed secret controller: docker.io/bitnami/sealed-secrets-controller:0.26.3

**Describe the bug**

When creating a sealed secret with a setting of spec.template.metadata.name different from the name of the sealed secret, a secret is created with name equal to metadata.name of the sealed secret. The metadata.name from the template section is ignored. 

**To Reproduce**

Create a sealed secret. 
Add an override for metadata.name in the template section. Example: 

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: passwordsecret-ss
spec:
  encryptedData:
    ARTIFACTORY_PASSWORD: YOUR_ENCRYPTED_SECRET_HERE
  template:
    metadata:
      name: passwordsecret
```
Now a secret named 'passwordsecret-ss' is created, not the expected secret 'passwordsecret'.

**Expected behavior**
In the above example, a secret with name 'passwordsecret' should be created. 

**Version of Kubernetes**:
kubectl version:
```
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4+k3s1
WARNING: version difference between client (1.29) and server (1.27) exceeds the supported minor version skew of +/-1
```

**Additional context**
