### ISSUE TITLE
kubeseal fails with timeout when controller is not deployed to primary API node specified in kubeconfig file

### ISSUE THREAD

**Issue by v1nsai** [bitnami-labs/sealed-secrets#1563]
**Which component**:
kubeseal version: 0.27.0

**Describe the bug**
When the sealed-secrets controller is deployed on a non-API node (not the node specified by .clusters[0].server in your kubeconfig file), it times out with an error similar to the following:
```
I0713 13:41:46.740369 3482215 request.go:1212] Response Body: {"kin":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"error trying to reach service: dial tcp 10.1.154.150:8080: i/o timeout","reason":"ServiceUnavailable","code":503}
error: cannot fetch certificate: error trying to reach service: dial tcp 10.1.154.150:8080: i/o timeout
```
**To Reproduce**

1. Deploy sealed secrets controller to a node that is not the one in your kubeconfig (or change your kubeconfig to a different node)
2. Run `kubeseal --fetch-cert --controller-name=sealed-secrets-controller --controller-namespace=flux-system`
3. See error

**Expected behavior**
I expected to get the public cert.

**Version of Kubernetes**:

- Output of `kubectl version`:

```
Client Version: v1.29.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4
```

**Additional context**

Kubeseal starts working as expected immediately if I update my kubeconfig to point to the node that sealed secrets controller is deployed to.  I have tested this on multiple nodes, the only thing that seems to matter is that sealed-secrets is deployed on the primary API node.

**Comment by agarcia-oss** [comment]
Hi @v1nsai what kind of cluster are you using_ This problem seems related to your kubeconfig settings rather than a Kubeseal issue.

**Comment by v1nsai** [comment]
I'm using microk8s v1.29.4

I should have specified that all of the nodes I have tested this on are master nodes, ie it shouldn't matter which one the kubeconfig is pointing to (correct?).  I just tested again and kubeseal still stops working as soon as kubeconfig is referencing any node that sealed-secrets-controller is not deployed on.

Here's my kubeconfig, line 5 is the only line that I have made any changes to.
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <certificate authority>
    server: https://192.168.1.155:16443 # kubeseal stops working if this is set to any node other than the one sealed-secrets-controller is deployed on
  name: microk8s-cluster
contexts:
- context:
    cluster: microk8s-cluster
    user: admin
  name: microk8s
current-context: microk8s
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: <client certificate>
    client-key-data: <client key>
```
