### ISSUE TITLE
Install in an isolated namespace

### ISSUE THREAD

**Issue by retr0h** [bitnami-labs/sealed-secrets#166]
I'm attempting to install sealed secrets helm chart into a namespace where my user is "admin" at the role level not the cluster level.  I was hoping to install sealed secrets in this namespace to isolate the users from needing access to other namespaces/secrets.

Am I being a numbskull here?

```---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ item.namespace }}-manager
  namespace: {{ item.namespace }}
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
```

```
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ item.namespace }}-binding
  namespace: {{ item.namespace }}
subjects:
{% for item in item.users | default([]) %}
- kind: User
  name: {{ item }}
  apiGroup: rbac.authorization.k8s.io
{% endfor -%}
roleRef:
  kind: Role
  name: {{ item.namespace }}-manager
  apiGroup: rbac.authorization.k8s.io
```
