### ISSUE TITLE
Helm versions newer than 2.4.11 no longer seem available

### ISSUE THREAD

**Issue by kenlasko** [bitnami-labs/sealed-secrets#1666]
**Describe the bug**
I am unable to upgrade Sealed Secrets using the Helm chart newer than 2.4.11 via ArgoCD. I get the following error:
```
Failed to load target state: failed to generate manifest for source 1 of 3: rpc error: code = Unknown desc = error fetching chart: failed to fetch chart: failed to get command args to log: `helm pull --destination /tmp/278d244c-cb20-43f0-9050-84015b346806 --version 2.4.12 --repo https://charts.bitnami.com/bitnami/ sealed-secrets` failed exit status 1: Error: invalid_reference: invalid tag
```
Reverting back to 2.4.11 works fine

**To Reproduce**
Create Sealed Secrets app in ArgoCD:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami/'
    targetRevision: 2.4.12
    chart: sealed-secrets
    helm:
      valueFiles:
      - $values/sealed-secrets/values.yaml
  - repoURL: 'git@github.com:kenlasko/K3S.git'
    ref: values
  - repoURL: 'git@github.com:kenlasko/K3S.git'
    path: sealed-secrets
    targetRevision: HEAD
    directory:
      exclude: '*_DISABLED.yaml'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
```

**Expected behavior**
I expect to be able to upgrade to a newer version of the Helm chart than 2.4.11

**Version of Kubernetes**: 1.31.4
