### ISSUE TITLE
Ability to customize the fieldManager used by kubeseal controller

### ISSUE THREAD

**Issue by VannTen** [bitnami-labs/sealed-secrets#1682]
**Which component**:
controller 0.28.0

**Is your feature request related to a problem? Please describe.**
I use the ability of kubeseal to patch secrets to manage non-sensitive key directly with argocd, and sensitive keys via a SealedSecrets in argocd.
In order to prevent argocd and sealed-secrets to fight over the secrets (because the patch would result in a difference with git state from the POV of argocd), I need to use the [ignoreDiff](https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#application-level-configuration)

```yaml
spec:
  ignoreDifferences:
  - group: "*"
    kind: "Secret"
    managedFieldsManagers:
    - controller
```

However, `controller` for the field manager does not clearly indicate we're referring to sealed-secrets.
Ideally, the default would be something more clear, but I think this would break backward compat, so a flag allowing to change the fieldmanager would probably be preferable.

**Describe the solution you'd like**
Have the controller use a fieldManager which reference more explicitely sealed-secrets.

**Describe alternatives you've considered**
Documenting in the argocd Config that 'controller' refer to sealed-secrets.
I don't know where that value come from (I've been unable to find it in the code), so I'm not sure if that could also collide with other controller. (=> which would lead to the argocd config having unintended effect).

**Additional context**
Given the manifests: 
```yaml
---
kind: Secret
apiVersion: v1
metadata:
  name: gitlab-forge-kube-gitops-credentials
  labels:
    argocd.argoproj.io/secret-type: "repo-creds"
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
stringData:
  type: git
  url: https://gitlab<REDACTED>/kube-gitops
  username: gitlab+deploy-token-158
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-forge-kube-gitops-credentials
spec:
  encryptedData:
    password: AgCVH43Ef3OutakFs2ezCc3x6itwo4e6NgEc7OV7gmGTzzR3D8tzjXNDb90ToyYwMEera27/WLuFLwVX68OuqjsHXgQkfxh6UXpg8eZi7DsSFBJ+xHc1X38n/HoLW5Hk6OV6IJY0VLCBIaMGuOHsG2S2TnjhaYFN5XftCG/gKsWfbSDZ5+vVaDfcb5Ya91XI2+D6y/xUH4bs2xO86qtDH/CxqWrdqqwToxNGMDs64xyVOg6x7rVO912OqLeR/Iw2znXp/yXWSVZ6ZfLtxzqJIKBr2i2S6Di5NuiR/xEvf93uOgtNu8kjMAWz6PGvpOOn0InaQIELZc7z+6A1xUe1SvwoWhgj0Dy14K1folbuMx74CUMQ+x5iXTlZeilOVZGMeylgSeqbfWw5zuQ07pDd8qlsM5/oHScwXyVNKIjlgwFdI1aoRwMqaBv5cwyARmaQW7AFnVaMnpsOIHGa4IrS9U+51akcxE0eMlheidquLun3Q1RVd5PbLxyfLW/7Ke93w99TTaZzzDAXhrqwnxy8RW76nEa5wi+w5RP9hdPk3EPWDHsDlEgwfDsIoCs/tSuM5axreH3me43gzyDoM9FMV+S9IbVCXaOnBSuTXJtoyC0+u/BYBeD3/JFUshbeMPm7dPRnde1NGu0mmNnN+Iwm6CQKIyNnT+4D4ABNttHhJh690uQ4SZJ8U7h+uD9mI1cweeXAnLfT6/dBX+1FZXvOfNMWZqnIHVxBfpUW
  template:
    metadata:
      name: gitlab-forge-kube-gitops-credentials
      namespace: argocd
```

If doing a `kubectl apply -f ` on the above, then `kubectl get --show-managed-fiels=true -o yaml secret gitlab-forge-kube-gitops-credentials` should show the managed fields. 
```yaml
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:type: {}
        f:url: {}
        f:username: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
          f:sealedsecrets.bitnami.com/patch: {}
        f:labels:
          .: {}
          f:argocd.argoproj.io/secret-type: {}
      f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2025-01-31T11:51:50Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:password: {}
    manager: controller
    operation: Update
    time: "2025-01-31T11:51:51Z"
```
