### ISSUE TITLE
Encryption without namesapce

### ISSUE THREAD

**Issue by benedictdudel** [bitnami-labs/sealed-secrets#240]
We have a CI/CD pipeline which creates a new namespace for every branch in our repository. Unfortunately we do not know the name of our namespaces ahead. Therefore we thought we could make us of Helm templating and our pipeline would create a new secret for each namespace. Have a look at the following example:

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-little-secret
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    XXX: XXX
  template:
    metadata:
      creationTimestamp: null
      name: my-little-secret
      namespace: {{ .Values.namespace }}
status: {}
```

As far as I can see when kubeseal creates a `SealedSecret` it automatically adds the namespace `default`. Would it be possible to allow dynamic namespaces in SealedSecrets? We would not like to use clusterwide secrets.
