### ISSUE TITLE
some metadata gets deleted after unsealing secret

### ISSUE THREAD

**Issue by tschonnie** [bitnami-labs/sealed-secrets#242]
we define some metadata in the sealed-secret manifest. however, when bitnami sealed-secret unseals secrets, in the original sealed-secret manifests those custom metadata gets deleted.

any idea why that happens?

**Comment by mkmik** [comment]
As described in the [README](https://github.com/bitnami-labs/sealed-secrets#sealedsecrets-as-templates-for-secrets) the metadata of the SealedSecret is distinct from that of the Secret.

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: mynamespace
  annotation:
    some-annotation: This one stays in the sealed secret
spec:
  template:
    metadata:
      annotations:
        some-other-annotation: This one goes in the unsealed secret
```

Make sure you're running sealed secrets (client and controller) above version v0.8.0.

Did this answer your question?

**Comment by tschonnie** [comment]
I understand that the Secret is distinct from the SealedSecret and that is totally ok for me.
However, I do not understand why the original metadata in the SealedSecret is deleted in the SealedSecret after creating the Secret object.

**Comment by tschonnie** [comment]
sealed-secret.yaml:

```
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: testsecret
  namespace: default
  creationTimestamp: 2019-09-06T11:27:02.106Z
  username: myUser
  issuer: KleJ
spec:
  encryptedData:
    password: >-
      AgCc15MsFkoplpEhHnJ/Ilz1TsNWknmT1H5CchHc8U9NNCeb3T7KUHB0nq3ZU40SYCSOjs1Uy/YdxHFUGI4nlZTdZYTXYP1vu4+6Rp0VKYjkkK+QUhR+kCzqQ4WXxdbBaTa1zL0Xd0aStbWpFBXZOTrOFg4qFD7ifa93vMPNGP/QpMxxW6tCTDO6oVWmQh6SudPH/sV7bnYs7+efB/uOBUAkas+V+w8OOX0NuheBRs7D6zdkCmnsLLui8Ncv0OkeyrA13oCJvJJ8NKuk/PS8OPUMeQagMceZ/pgCYkkRZhmnGFk+D7HUfxEOL7om1TxwilPBMlA/uPQypU5tV/DY1ESiGF2HnuYTNYNMB+u7aUDkVQUppxW9AwMzx4JxZ194h737fOpm7nDvCN3kqll7hGoBxmOZvPOLU3wrCvXIorRQE1ct2WQs3+ZyiCFfsxuSzhFxfd6+HXxpRFJYgez5TsMnhpVka3SMdfJUheG4rrWiSiciyOZFr1V7WehRu7MAERj4JGulktushxoPL+o2coJ7rIZMza9+Q57WA7xPkb3DAQFKCLBWrazu6KMMR56jXPzy67bfamD18cEuwV0IbCoqyEi6HNCOqustmJ+Q8pTMSV895wKe1tGFtUXGZbueYFrxUS1EmntrqCDj3Dvi8ZH5ImDfdtXwl37mg7YN4oWWgOwX02oS8FR/kcJaLML8LVqyUfY0gm9UqkuA
    username: >-
      AgA2j4+qNnDsUVANKaoE689grc6rcHyhg68DC2scFuqT2gLzFCC/Mk7w1L+NbHdDtxjONqHcfSMZTaxg+Y7Og17yQKd0GeFcQZKDUFj5dpi+TdLGRYHRhAkvJUJ2gzbWh1f2DvBwMCdWSyqm2Q7aZff/BqFiLp5YiRQF3cUYw7Ec++Zp0Rq9qiYJbLy17vj838nmXSU9JOpdENzR1ELkycEQ7hK/PsmDSEB972DZINGyIIaS+pIEQQVV8iIvJ8//HgCBeovcB/VxXPl1p5hkuGtN0ATljo792afYZ4KrLyx8JL6WVM40x2dE6KZiV1ztIyzjCU/K1ZxFtWsiUfJgVuhnYnOshUhact6PtxedYmQoGf2Zh+2x7MzTxBBI2uuToE1Z+mIYASdWLsPnb+oDAdAl7it3S90/UNEN+j+j1A7ufrJoTrkZQtugQyrKasZblyHGr2538BJmS6JaBE4TQbHJbcJ+NenreTmCeXLHBKnkWU5fwAwD0sQjSEUWcN1y3by4Brck21pSpJXn8IzzIjNtIdF/uYyFaT/GMcv4D8u4eMDsD27WIWLoE0+HyaMh78vzJ8Q2SqZ/IUJjomDdLUfJ8+iWX+Y48HSGK0qt3VuZ6cAfuh2xwtdgkkJb/LpIrwSJ270I4179Rqd9Ehqq4aOIOuWNhEoYk9ji5G3C0kDQIqMJohcBFePUghcVE+0aEi8LOdVU9o4=
```

after "kubectl apply -f sealed-secret.yaml" a secret gets created and in the original SealedSecret the metadata "username" and "issuer" is not there anymore.

**Comment by mkmik** [comment]
ah, this seems to be a different problem.

I don't think `username` and `issuer` are valid fields of the k8s `metadata` object.

You can the find the k8s API reference here: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#objectmeta-v1-meta

You can clearly see the error if you try to add this field to a secret object

```bash
$ kubectl edit secret testsecret
...
# secrets "testsecret" was not valid:
# * : Invalid value: "The edited file failed validation": ValidationError(Secret.metadata): unknown field "username" in io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
```

Did you mean:

```yaml
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: testsecret
  namespace: default
  creationTimestamp: 2019-09-06T11:27:02.106Z
  annotations:
    username: myUser
    issuer: KleJ
spec:
  encryptedData:
    password: >-
      AgCc15MsFkoplpEhHnJ/Ilz1TsNWknmT1H5CchHc8U9NNCeb3T7KUHB0nq3ZU40SYCSOjs1Uy/YdxHFUGI4nlZTdZYTXYP1vu4+6Rp0VKYjkkK+QUhR+kCzqQ4WXxdbBaTa1zL0Xd0aStbWpFBXZOTrOFg4qFD7ifa93vMPNGP/QpMxxW6tCTDO6oVWmQh6SudPH/sV7bnYs7+efB/uOBUAkas+V+w8OOX0NuheBRs7D6zdkCmnsLLui8Ncv0OkeyrA13oCJvJJ8NKuk/PS8OPUMeQagMceZ/pgCYkkRZhmnGFk+D7HUfxEOL7om1TxwilPBMlA/uPQypU5tV/DY1ESiGF2HnuYTNYNMB+u7aUDkVQUppxW9AwMzx4JxZ194h737fOpm7nDvCN3kqll7hGoBxmOZvPOLU3wrCvXIorRQE1ct2WQs3+ZyiCFfsxuSzhFxfd6+HXxpRFJYgez5TsMnhpVka3SMdfJUheG4rrWiSiciyOZFr1V7WehRu7MAERj4JGulktushxoPL+o2coJ7rIZMza9+Q57WA7xPkb3DAQFKCLBWrazu6KMMR56jXPzy67bfamD18cEuwV0IbCoqyEi6HNCOqustmJ+Q8pTMSV895wKe1tGFtUXGZbueYFrxUS1EmntrqCDj3Dvi8ZH5ImDfdtXwl37mg7YN4oWWgOwX02oS8FR/kcJaLML8LVqyUfY0gm9UqkuA
    username: >-
      AgA2j4+qNnDsUVANKaoE689grc6rcHyhg68DC2scFuqT2gLzFCC/Mk7w1L+NbHdDtxjONqHcfSMZTaxg+Y7Og17yQKd0GeFcQZKDUFj5dpi+TdLGRYHRhAkvJUJ2gzbWh1f2DvBwMCdWSyqm2Q7aZff/BqFiLp5YiRQF3cUYw7Ec++Zp0Rq9qiYJbLy17vj838nmXSU9JOpdENzR1ELkycEQ7hK/PsmDSEB972DZINGyIIaS+pIEQQVV8iIvJ8//HgCBeovcB/VxXPl1p5hkuGtN0ATljo792afYZ4KrLyx8JL6WVM40x2dE6KZiV1ztIyzjCU/K1ZxFtWsiUfJgVuhnYnOshUhact6PtxedYmQoGf2Zh+2x7MzTxBBI2uuToE1Z+mIYASdWLsPnb+oDAdAl7it3S90/UNEN+j+j1A7ufrJoTrkZQtugQyrKasZblyHGr2538BJmS6JaBE4TQbHJbcJ+NenreTmCeXLHBKnkWU5fwAwD0sQjSEUWcN1y3by4Brck21pSpJXn8IzzIjNtIdF/uYyFaT/GMcv4D8u4eMDsD27WIWLoE0+HyaMh78vzJ8Q2SqZ/IUJjomDdLUfJ8+iWX+Y48HSGK0qt3VuZ6cAfuh2xwtdgkkJb/LpIrwSJ270I4179Rqd9Ehqq4aOIOuWNhEoYk9ji5G3C0kDQIqMJohcBFePUghcVE+0aEi8LOdVU9o4=
```

**Comment by mkmik** [comment]
... if yes, then you'll see that these annotations will be visible in the sealed secret but not in the generated secret.

You probably want:

```yaml
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: testsecret
  namespace: default
  creationTimestamp: 2019-09-06T11:27:02.106Z
spec:
  template:
    metadata:
      annotations:
        username: myUser
        issuer: KleJ
  encryptedData:
    password: >-
      AgCc15MsFkoplpEhHnJ/Ilz1TsNWknmT1H5CchHc8U9NNCeb3T7KUHB0nq3ZU40SYCSOjs1Uy/YdxHFUGI4nlZTdZYTXYP1vu4+6Rp0VKYjkkK+QUhR+kCzqQ4WXxdbBaTa1zL0Xd0aStbWpFBXZOTrOFg4qFD7ifa93vMPNGP/QpMxxW6tCTDO6oVWmQh6SudPH/sV7bnYs7+efB/uOBUAkas+V+w8OOX0NuheBRs7D6zdkCmnsLLui8Ncv0OkeyrA13oCJvJJ8NKuk/PS8OPUMeQagMceZ/pgCYkkRZhmnGFk+D7HUfxEOL7om1TxwilPBMlA/uPQypU5tV/DY1ESiGF2HnuYTNYNMB+u7aUDkVQUppxW9AwMzx4JxZ194h737fOpm7nDvCN3kqll7hGoBxmOZvPOLU3wrCvXIorRQE1ct2WQs3+ZyiCFfsxuSzhFxfd6+HXxpRFJYgez5TsMnhpVka3SMdfJUheG4rrWiSiciyOZFr1V7WehRu7MAERj4JGulktushxoPL+o2coJ7rIZMza9+Q57WA7xPkb3DAQFKCLBWrazu6KMMR56jXPzy67bfamD18cEuwV0IbCoqyEi6HNCOqustmJ+Q8pTMSV895wKe1tGFtUXGZbueYFrxUS1EmntrqCDj3Dvi8ZH5ImDfdtXwl37mg7YN4oWWgOwX02oS8FR/kcJaLML8LVqyUfY0gm9UqkuA
    username: >-
      AgA2j4+qNnDsUVANKaoE689grc6rcHyhg68DC2scFuqT2gLzFCC/Mk7w1L+NbHdDtxjONqHcfSMZTaxg+Y7Og17yQKd0GeFcQZKDUFj5dpi+TdLGRYHRhAkvJUJ2gzbWh1f2DvBwMCdWSyqm2Q7aZff/BqFiLp5YiRQF3cUYw7Ec++Zp0Rq9qiYJbLy17vj838nmXSU9JOpdENzR1ELkycEQ7hK/PsmDSEB972DZINGyIIaS+pIEQQVV8iIvJ8//HgCBeovcB/VxXPl1p5hkuGtN0ATljo792afYZ4KrLyx8JL6WVM40x2dE6KZiV1ztIyzjCU/K1ZxFtWsiUfJgVuhnYnOshUhact6PtxedYmQoGf2Zh+2x7MzTxBBI2uuToE1Z+mIYASdWLsPnb+oDAdAl7it3S90/UNEN+j+j1A7ufrJoTrkZQtugQyrKasZblyHGr2538BJmS6JaBE4TQbHJbcJ+NenreTmCeXLHBKnkWU5fwAwD0sQjSEUWcN1y3by4Brck21pSpJXn8IzzIjNtIdF/uYyFaT/GMcv4D8u4eMDsD27WIWLoE0+HyaMh78vzJ8Q2SqZ/IUJjomDdLUfJ8+iWX+Y48HSGK0qt3VuZ6cAfuh2xwtdgkkJb/LpIrwSJ270I4179Rqd9Ehqq4aOIOuWNhEoYk9ji5G3C0kDQIqMJohcBFePUghcVE+0aEi8LOdVU9o4=
```
