### ISSUE TITLE
Unable to unseal after new secret is apended

### ISSUE THREAD

**Issue by adeleglise** [bitnami-labs/sealed-secrets#285]
Hi,

We're hapily using sealed-secrets with gitops flux. We've managed to transform all our flat yaml secrets file into sealed secrets.

However, everytime we try to add a new entry in a sealedsecret file, the sealed-secret-controller fails to unseal them in kubernetes :

```
2019/10/02 12:13:17 Updating development/api-redacted-secrets                                                                                                                                                   
2019/10/02 12:13:17 Error updating development/api-redacted-secrets, will retry: no key could decrypt secret
2019/10/02 12:13:17 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"development", Name:"api-redacted-secrets", UID:"0430a1d0-e50e-11e9-9b5e-ac1f6b90cfa0", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"9327824", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret                                                                                       
2019/10/02 12:13:17 Updating development/api-redacted-secrets                                                                                                                                                   
2019/10/02 12:13:17 Error updating development/api-redacted-secrets, giving up: no key could decrypt secret E1002 12:13:17.686678       1 controller.go:192] no key could decrypt secret                                                                                                                                    
2019/10/02 12:13:17 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"development", Name:"api-redacted-secrets", UID:"0430a1d0-e50e-11e9-9b5e-ac1f6b90cfa0", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"9327824", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret
```

We've tried to extract the key, and it's the same a we use to seal the secrets, as told in the documentation.

What are we doing wrong ?

**Comment by mkmik** [comment]
hi! How do you add the new entry?
Which version of the client and controller?
Are you familiar with [scopes](https://github.com/bitnami-labs/sealed-secrets#scopes)?

**Comment by adeleglise** [comment]
We add the new entry by adding a field and resealing the file.

client: kubeseal version: v0.8.3 
controller: sealed-secrets-controller:v0.8.3

I've just read about scopes.

**Comment by mkmik** [comment]
> We add the new entry by adding a field and resealing the file.

As in editing a Secret in a local file, and calling `kubeseal <secret.yaml >sealed.json` again?

Could you paste here a full example (as faithful as possible, modulo the actual secrets of course)?

**Comment by adeleglise** [comment]
Yup.
We've firstly transformed all of our existing secrets :

```
kubeseal --format=yaml --cert=pub-cert.pem < api-redacted.yaml > api-redacted.yaml
```
This is working fine.

When adding a secret, we're doing :
```
kubectl -n development create secret generic api-redacted-secrets \
--from-literal=REDACTED_KEY=SECRET
--dry-run \
-o json > api-redacted-secrets.json
kubeseal --format=yaml --cert=./secrets/dev/pub-cert.pem < api-redacted-secrets.json > api-redacted-tmp-secrets.yaml
```
Then get the key from the tmp file and add it in the secrets file.

**Comment by mkmik** [comment]
1. is `pub-cert.pem` the same file as `./secrets/dev/pub-cert.pem`?

2. is the name and namespace of `api-redacted.yaml` in the first snippet `api-redacted-secrets` and `development` respectively?

In the meantime, by wild guess is:

The most common error is using a bad name/namespace/scope.
The "Scopes" section should explain why it matters to have a consistent name+namespace by default, and how to relax this constraint if needed.

---

Your use case would benefit from the new [`--merge-into`](https://github.com/bitnami-labs/sealed-secrets#update-existing-secrets) feature or the [`--raw`](https://github.com/bitnami-labs/sealed-secrets#raw-mode-experimental) feature.

The `--merge-into` feature has the potential of catching such errors, but it currently doesn't yet do that.

**Comment by adeleglise** [comment]
The pub-cert.pem is indeed the same file.

All the secrets, sealed-secrets, deployments and such belongs in the same namespace for this particular exemple.

We'll surely use the `--merge` option from now on :)

**Comment by mkmik** [comment]
> All the secrets, sealed-secrets, deployments and such belongs in the same namespace for this particular exemple.

what about the resource name? does the name in the first yaml match the same you later pass to `... create secret generic XXXX` ?

ah another thing: do you have any annotations matching the `sealedsecrets.bitnami.com/` prefix in your first yaml (api-redacted.yaml)?

**Comment by adeleglise** [comment]
The resource name is the same.

However, there's no annotations in the yaml :

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-redacted-secrets
  namespace: development
spec:
  encryptedData:
    REDACTED_SECRET_NAME1: encrypted_secret
    REDACTED_SECRET_NAME2: encrypted_secret
    REDACTED_SECRET_NAME3: encrypted_secret
    REDACTED_SECRET_NAME4: encrypted_secret
  template:
    metadata:
      labels:
        app: api-redacted
        stage: development
      name: api-redacted-secrets
      namespace: development
    type: Opaque
```

**Comment by mkmik** [comment]
Please try this container image: `quay.io/bitnami/sealed-secrets-controller@sha256:ef7a3da459ec05e5c50fa3c6971b97a1543c7e368f4c593839bfbd9500afdac7` it contains improvements in the error/event logging which might help us shed some light

**Comment by adeleglise** [comment]
Ok, I do it right now.

Will this change the actual sealing key ?

**Comment by mkmik** [comment]
no, it's just an unreleased build of the controller

**Comment by adeleglise** [comment]
Ok, it's here.

```
Starting sealed-secrets controller version: 40ddea622442c741827160836fd500cd7584e426+dirty
...
2019/10/02 13:21:18 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"development", Name:"api-redacted-secrets", UID:"REDACTED_UID", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"9327824", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret (REDACTED_SECRET_NAME)
```
Still the same error log. All the other files, are unsealed correctly.

**Comment by mkmik** [comment]
the `(REDACTED_SECRET_NAME)` should be `(REDACTED_KEY)`, does that match the newest name of the most recent secret entry you created with `--from-literal=REDACTED_KEY=SECRET`?

would you mind going through the excercise of actually creating a new secret with not-really-secret values, and then adding a new entry and pasting here verbatim the whole process. I have the feeling that during the redaction process we might be losing important hints for the troubleshooting process.

**Comment by adeleglise** [comment]
Yes, that matches. It's me when I mask the values :p

So I'm not using the `--merge-into` for the sake of reproducing the original steps :
```
cd gitops/secrets/dev
kubectl -n development create secret generic api-redacted-secrets --from-literal=TROUBLESHOOT=adding_a_new_secret --dry-run -o json > api-redacted-secrets.json
kubeseal --format=yaml --cert=pub-cert.pem < api-redacted-secrets.json > api-redacted-tmp-secrets.yaml
```

In the api-redacted-secrets.json :
```json
{
    "kind": "Secret",
    "apiVersion": "v1",
    "metadata": {
        "name": "api-redacted-secrets",
        "namespace": "development",
        "creationTimestamp": null
    },
    "data": {
        "TROUBLESHOOT": "YWRkaW5nX2FfbmV3X3NlY3JldA=="
    }
}
```

In the yaml:
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-redacted-secrets
  namespace: development
spec:
  encryptedData:
    TROUBLESHOOT: AgCSmlNQozdNPfu+Jx9onUrfpjqllLIhny1VonhWTzY019al7KbVh1+8zdZahgEp5uvKAR9XsxzgAod8JiMxPBCOtRH1c9oLbtTIDIZm8OUYykG1y9zxjh1asB+CY6fKjFSO86w2BkNvzlV1stab4BXIZo5DQxPBClHVb7e1bjCAy0xxiQZP+NNKj5uKT2wd1BaXa2YH5J4VsjvvB3B/KafbrnBFUijFFmrC5N8jsndEwwWHgm4yWsYw7OcrTfy6WCNOKqOfalBIksmj8Jj5c0cpKLPcIwm9M4PW/LiYxOcfcbI5J/hDAwZofLpwklrdjG972YGtT9hj2N98zgx+7I80Hou2K1rLFLISkm06lgk3t+mtcm0LSOtsDUq9TuGsJrZBgxoa2b0wl9vBTtPB0SIZKVQdqkbN0e1k2JRZg68UxZpGKbuXuCnGUjpn3NwywTWVoE8w7oswQUc+alA/sa+1InNv5QopHLMmiVqmSaen3++VhKcf822W4mMESKseM2hPHvmQBYCu3ed0KkJQDNXkFVtnOXsXp9ouQ3Nzw7PbzysOVYMim+jeF/ViQH8x8+mUTzY6XIs74H7Gb97I/0az8riOrHZGq70soM1ndMX76gPgiS1LJC+v+YlV4yPwCLTUJH46VeZK/wpAwRiZoJN8EKLIKEyMKDVvqMd2+Nh6lpYRradw4L0JY8hHnnWGuSuvt9xvUqajw2LhqC8tz0qSdfCs
  template:
    metadata:
      creationTimestamp: null
      name: api-redacted-secrets
      namespace: development
status: {}
```

Then I take the line `TROUBLESHOOT: AgCSmlNQozdNPfu+Jx9onUrfpjqllLIhny1VonhWTzY019al7KbVh1+8zdZahgEp5uvKAR9XsxzgAod8JiMxPBCOtRH1c9oLbtTIDIZm8OUYykG1y9zxjh1asB+CY6fKjFSO86w2BkNvzlV1stab4BXIZo5DQxPBClHVb7e1bjCAy0xxiQZP+NNKj5uKT2wd1BaXa2YH5J4VsjvvB3B/KafbrnBFUijFFmrC5N8jsndEwwWHgm4yWsYw7OcrTfy6WCNOKqOfalBIksmj8Jj5c0cpKLPcIwm9M4PW/LiYxOcfcbI5J/hDAwZofLpwklrdjG972YGtT9hj2N98zgx+7I80Hou2K1rLFLISkm06lgk3t+mtcm0LSOtsDUq9TuGsJrZBgxoa2b0wl9vBTtPB0SIZKVQdqkbN0e1k2JRZg68UxZpGKbuXuCnGUjpn3NwywTWVoE8w7oswQUc+alA/sa+1InNv5QopHLMmiVqmSaen3++VhKcf822W4mMESKseM2hPHvmQBYCu3ed0KkJQDNXkFVtnOXsXp9ouQ3Nzw7PbzysOVYMim+jeF/ViQH8x8+mUTzY6XIs74H7Gb97I/0az8riOrHZGq70soM1ndMX76gPgiS1LJC+v+YlV4yPwCLTUJH46VeZK/wpAwRiZoJN8EKLIKEyMKDVvqMd2+Nh6lpYRradw4L0JY8hHnnWGuSuvt9xvUqajw2LhqC8tz0qSdfCs`

I add it in the existing sealedsecret file, commit/push to the gitops repo. Then flux see that the file has changed and apply it.
