### ISSUE TITLE
How to apply sealed secret with kustomize?

### ISSUE THREAD

**Issue by WonJaesub** [bitnami-labs/sealed-secrets#297]
Hi.
I practice using sealed secret, but it doesn't work with kustomize.
When I try without kustomize, it worked.
What's wrong in my code?

```
$) kubectl create secret generic echo-secret --dry-run --from-literal=PORT=4000 -n ope-won -o yaml > echo-secret.yaml
$) kubeseal -o yaml <echo-secret.yaml >echo-secret-ss.yaml

$) cat echo-secret-ss.yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: echo-secret
  namespace: ope-won
spec:
  encryptedData:
    PORT: (encrypted)
  template:
    metadata:
      creationTimestamp: null
      name: echo-secret
      namespace: ope-won
status: {}
```

result with kustomize (prefix: `naruke-` )
```
$) kubectl describe sealedsecret naruke-echo-secret
Name:         naruke-echo-secret
Namespace:    ope-won
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"bitnami.com/v1alpha1","kind":"SealedSecret","metadata":{"annotations":{},"name":"naruke-echo-secret","namespace":"ope-won"}...
API Version:  bitnami.com/v1alpha1
Kind:         SealedSecret
Metadata:
  Creation Timestamp:  2019-10-24T05:46:10Z
  Generation:          1
  Resource Version:    33150228
  Self Link:           /apis/bitnami.com/v1alpha1/namespaces/ope-won/sealedsecrets/naruke-echo-secret
  UID:                 94ed2f09-f621-11e9-b7e8-06f5276ae486
Spec:
  Encrypted Data:
    PORT:  (encrypted)
  Template:
    Metadata:
      Name:       echo-secret
      Namespace:  ope-won
Status:
Events:
  Type     Reason           Age                    From            Message
  ----     ------           ----                   ----            -------
  Warning  ErrUnsealFailed  3m32s (x6 over 3m32s)  sealed-secrets  Failed to unseal: No key could decrypt secret
  Warning  ErrUnsealFailed  3m32s (x6 over 3m32s)  sealed-secrets  Failed to unseal: no key could decrypt secret (PORT)
```

result without kustomize(`kubectl apply -f echo-secret-ss.yaml`)
```
$) kubectl describe sealedsecret echo-secret
Name:         echo-secret
Namespace:    ope-won
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"bitnami.com/v1alpha1","kind":"SealedSecret","metadata":{"annotations":{},"creationTimestamp":null,"name":"echo-secret","nam...
API Version:  bitnami.com/v1alpha1
Kind:         SealedSecret
Metadata:
  Creation Timestamp:  2019-10-24T05:46:52Z
  Generation:          1
  Resource Version:    33150384
  Self Link:           /apis/bitnami.com/v1alpha1/namespaces/ope-won/sealedsecrets/echo-secret
  UID:                 ae191c72-f621-11e9-b7e8-06f5276ae486
Spec:
  Encrypted Data:
    PORT:  (encrypted)
  Template:
    Metadata:
      Creation Timestamp:  <nil>
      Name:                echo-secret
      Namespace:           ope-won
Status:
Events:
  Type     Reason           Age    From            Message
  ----     ------           ----   ----            -------
  Warning  ErrUpdateFailed  2m33s  sealed-secrets  secrets "echo-secret" already exists
  Normal   Unsealed         2m33s  sealed-secrets  SealedSecret unsealed successfully
  Normal   Unsealed         2m33s  sealed-secrets  SealedSecret unsealed successfully
```
