### ISSUE TITLE
Secrets encrypted using raw mode are not decrypted

### ISSUE THREAD

**Issue by pkaramol** [bitnami-labs/sealed-secrets#322]
I have created a GKE cluster and deployed sealed secrets controller.

I want to create a helm chart that will also incorporate a `SealedSecrets` resource.

I want to use raw mode to fill my `values.yaml` file. 

So for example I run:

```
▶ echo -n foo | kubeseal --cert=/Users/panteliskaramolegkos/Workspace/hidden/mycert.pem --raw --from-file=/dev/stdin --namespace default --name postgresql://postgres:foobar@postgres/postgres
AgCbvJzxeoATE5BPy5NPAI/PWgYRxTXLw5ZxbwniL3Pmjn/undqa/eBK+I4HT5CJi0A6yQLWlpOCLkgw2eTrfIlZeqBDo8HOmjzx2N0fgH5sN7ge7JeI1mZOkNpwmW89ggLqRNxIKHqVumzsC0niqhMplrMzl0nBAcdCxyTm2FDUVHXoAZ1IhahCceqbl5XVh9jJImRI/tVzyA1E5X6uaK9NGmPltABb3pu0uHhaQutC7NdfKUaW15y5Q8CwiSI45oBybjrVpjxcZnwXRPlI9eYB+bk7Dzczqtuwv0BcXGq5f2Ig4PKgYikQmhLkbt6fZB7rt9WmfHVu2+MmkaX7jXEzISV6oCerUVWq2xSzSKhyp4q8HC/Zxdi36bXSb5zALfI6A4ePmNVPnEqDMMEHpKX2jJyF35R5Go3gjghK77GFZ9GfLNa0qNl4MdnAzRsickEI8ZqQ2+o+jGGqIidjTE831lplVZWFbwO6cB3cEnlj2MDm0a3EURb3mPHrRwE33c95T6gFIEcaUZjsGQoZ7lz6GTdSyphA6jVJymNqSw8RSQKyy+X+itUJSfsNhXCgC63fn26tgWDJrdAEIxPjoloUTyCPzELIgX4bWf80SqLDgtPhcE1j9gWMDzQa6AdJcv8nWxGDYnQhdGyj4Djz1Z+XWVbebZ2XApK+faVjQQTlxntrpvP6C8rfukD9HUJSzxqazNE=
```

Then I create my `values.yaml` file by copying and pasting the specific value.

The secret(s) fail to get decrypted and the error message on the logs is:

```
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets 2019/11/22 15:36:54 Updating default/sanguine-olm-secret
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets 2019/11/22 15:36:54 Error updating default/sanguine-olm-secret, giving up: no key could decrypt secret
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets E1122 15:36:54.523177       1 controller.go:194] no key could decrypt secret
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets 2019/11/22 15:36:54 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"default", Name:"sanguine-olm-secret", UID:"e90eeb9f-0d3d-11ea-8312-42010aa40fc8", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"285309", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret
```

Working on GKE with

```
▶ k version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-gke.14", GitCommit:"56d89863d1033f9668ddd6e1c1aea81cd846ef88", GitTreeState:"clean", BuildDate:"2019-11-07T19:12:22Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```

Unfortunately, the following command never returns:

```
▶ kubeseal --controller-name=redash-sealedsecret-release-sealed-secrets version
(tty detected: expecting json/yaml k8s resource in stdin)
```

__Detailed Walkhtrough__:

Here is the environment file with my secrets:

```
▶ cat redash_local.properties
POSTGRES_PASSWORD=foobar
REDASH_DATABASE_URL=postgresql://postgres:foobar@postgres/postgres
REDASH_COOKIE_SECRET=foobar
REDASH_SECRET_KEY=foobar
```

Encrypting with `kubeseal`

```
▶ k create secret generic redash-secret -n default --dry-run --from-env-file=/Users/panteliskaramolegkos/Workspace/hidden/redash_local.properties -o yaml | kubeseal --controller-name=redash-sealedsecret-release-sealed-secrets> ~/Desktop/sealedsecret.json
```

Here is the file produced:

```json
▶ cat ~/Desktop/sealedsecret.json
{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "redash-secret",
    "namespace": "default",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "redash-secret",
        "namespace": "default",
        "creationTimestamp": null
      }
    },
    "encryptedData": {
      "POSTGRES_PASSWORD": "AgAlVDwewStlSetsptIjV0/ZGp+PEt/Mtyga1mOLSGBu4X5L3F5meVYLym+3Ow4YilaXpMm7peq4MXJDk1GXmhBLugJEisN1kvlyKWLh0Gktu5fJFO0F8vFsQg7WgHWpmPnJiS3kfNyaRgfBSzo+v5b3USFYcFKcl5WmQFonQ69NgHM0BZKqOH4egC195DdfvI7SudokWfZYnZLUOU5t0U/zS5YvUPugoGycZ/dNSoKfV+/a9/+LrZsLEd5YP9s2cGJG4zr9WmEmaBPYRa50+pcbJlMkl8zhk7iq8zzQxC+kSm3wcbMK8JJ6z57tU8ghsV6HJZkWmkNBL1w39uPMD9imnwFEsFYRoMgjEHSh7s+LvoBsToZJ53+WrWhIqsxRczwSIfboCIaDBVxNW1HCj8OgijGdWGN94SGOdb8+mwRKyDJ7vlqIEs/xVDgbQG2LrNYGeEFKftR/0pTZ0JNxeMoHH/pPCtXniXgaPMye+usfgoZ+5iJEjv2mws1uRpFwwbE2zWPlohbZ9QWSPuTs4KICcWt+FzzN3Hypm97yHZPcFYZj748b5Rwh84h0baofDEoVPr/K4YY0XIeAg3GqGCOqFQk/wqaneYzc5jutDfdH8FqH2mqIfpl2HTjW8MHfwXKPu4Hxw2aUFHCZud1Z3rK+Xur8rYRNi8x0+wn8jufPPehTBNBZMR5PBpbog9aY6XHQYEyumH4=",
      "REDASH_COOKIE_SECRET": "AgBqenc9YSB5/HktdQYeZCUCgEEhLHDzGivlLCNStcxNsw0AsE3gdzof5EOcDx71xXurjr2OggjLhQl2TjGya87ce8An63TgUCJmx1U5DSL4n5C+Tw6ZROoych7XU0p02wRSf9wZapEtizcNqeITfSPdYUymO2qSgfUfCI+mJNelXQOi2Y5cveFnJ8Q6TNuIq2pvFlzaicmpcXD5PFSvI2+pkchEGr8UYpOhVEYe7R83ypDED9D1L0t4jaul5ZVdVz04nPqPxMrTvIc+ntnZb6gLGvav3UI7T/UaN6xuXw87dAYVCyse+APYNafwgXu/RvXfT0kcRU5wtQTxT1bMQrE8DCOMrSQUvP7MRLHifspCmx02HXz0wg9l1coZVgjW5HYV2w+P+sfdnDHXxz1h2IsU1OzAR9PWUhgC3pV34lFSBH/rTDwsZV5cNWNuw3NslL8VNmktPuzDZcrXgNkWnBzcrSP/RnAZmdnMp3bC17plF2VBVUwJLDLXM6xkLRBrp+4UKl1z0LuUNt7rz5/5+hhWU5A5tgy2SxxsfT6u9AuaesH+65OgVNgJlZoNI0Y+i5yI2rIIb72UjAnuTok7TzFNqfqlVOOL6ftB/P2jJh81XSdLWuCaaGyp5cp/YXkeflTCIOwUruLUOOh7pAXjntU1v9CD8zH11gqgQIh6Mse05eH9VUTXAPTDTn5Rdyu7ZwPufYVfQvM=",
      "REDASH_DATABASE_URL": "AgCQsjejiQh2MiTSRo7O01J6Z/jBdjXZ6ju5gtEZW9fo6nyMQOPt6v/50TrN/l+1RIGdyCAk9P1SNdyoY7Q+SdDsiGWno/Wpq8WmOXxe3ohDG/B3j33GSXtQDhSZ6z0Q3qYZ4uorAvai1fyXXNoR0sCZwJGutV4ZWBUEKZ7+1Ib2maLrei4FNQ8guQ5f17mkykzVOuoCGIOSGjsVv2QOSoS0wxjf2mdNbFd8wyqj64ovxcy2aKONLTxUQm02/w2yeuLDMnDNSefuZGXoI77zrAfS+2vhbqoP0Sae53otpWhBiZ8M4q/kvA26AHKO9TZ2gaJNRsJhnOIyjeVjj5UcbNS0rQB23j3vIGbrw4DxIsPb4v0FZ5sGOdHHWUh3KyC8bgpEZZzl94VROXh/RypuysSh/jpBbWsPMlKC8a6Qj6BuTYYkEUHJFjykHQhFhcpEfXluFgOut2ZpIRyNWMvvNfEfUF0OsWg5scxevf51Rmuuc4lEYVCTppNxW8qk/TxiIzPKQoEoNDJGt1wSusi5x1yYMiv7GFZCEZfK5siTR34gsGQsN+jg4owQrPgP3cHUdnzI38ugSBNh0hYYx/Zq3RIsTxotEUFVLv0pxxNuH5mVQA33ZJpdLfGI0SvIxdERBwQRFTV31bwXGhNY7fDyE7LKibaNWWCmmsCnwUdsYBLGtk6+G0uON5j4TBFImtlUh0hh9E9xW4BDL9FwO1JTPg/foFpmlwtTGSiM6SKYupKabLJ5BzGFq1KrpokFsg9B",
      "REDASH_SECRET_KEY": "AgBbhDUuEUcGsecettOP8uj6F/QJq29czPk3HsHgNO9BmUYq/H/EOpfnEQQ75rutMiUhMHFt8+unUC2nkqbMh5LoKpIJONYfi99sza3MIWJHPl/mIAQhyXflXkjo2z2Rw8Ch6BxDQ8Byj5ODG1sPSvHY5LmGY7twNuCPR9rgI7fFl+x2Y588B7VgESCTim1MQtN5Xr5mawiYVZqcDAqyeTTaxV/VBP0DDRrimHpWma/3bmmGvvY18sIjLigX7Z9XaFhCmdp8dPFXr1Ul7L2NdNMI9qhtyhTkJbgZ6IzyCcE+umImVNe81N2RRYnX1zE6YGdUVvbSJ+oj1FmHQ1V1e2pGtIJpVltl+OWOyN9ToSlKrYyciDkoO60x3xfxOX8tcoWPiMc1wjLX5YAViYjucat0tXJrfrUxf8F98gtHi9gRY2wFJaN3MYbM9UJ77Q7Is1yDSrSaYJmBr12BRoU0xpGRQXsHKGKEj4dxiFDAVfKW4apHg7YQSX0qAYr0+w4lFCZM7rGGcd3i5CC7iwRqWcRv1GX4XH7KLmjhvXz043PHcL62v9xvuNHQHlLG06Uw5TNvoI5m5dPYFQ29LzoUu5DOlcznLIp+TH27Y6SwFFJO1Sf4BZGhJMj3rulAMC0dREc6nI2VViDlEoWtaip9XUUuWQyKdAWKWZvvipWVPZz5keUoONFoIzl3ohlwHHy/ywirm7Kvl9s="
    }
  },
  "status": {

  }
}
```

converting it to `yaml` to place it directly in my `helm` templates:

```yaml
---
kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: redash-secret
  namespace: default
  creationTimestamp: 
spec:
  template:
    metadata:
      name: redash-secret
      namespace: default
      creationTimestamp: 
  encryptedData:
    POSTGRES_PASSWORD: AgAlVDwewStlSetsptIjV0/ZGp+PEt/Mtyga1mOLSGBu4X5L3F5meVYLym+3Ow4YilaXpMm7peq4MXJDk1GXmhBLugJEisN1kvlyKWLh0Gktu5fJFO0F8vFsQg7WgHWpmPnJiS3kfNyaRgfBSzo+v5b3USFYcFKcl5WmQFonQ69NgHM0BZKqOH4egC195DdfvI7SudokWfZYnZLUOU5t0U/zS5YvUPugoGycZ/dNSoKfV+/a9/+LrZsLEd5YP9s2cGJG4zr9WmEmaBPYRa50+pcbJlMkl8zhk7iq8zzQxC+kSm3wcbMK8JJ6z57tU8ghsV6HJZkWmkNBL1w39uPMD9imnwFEsFYRoMgjEHSh7s+LvoBsToZJ53+WrWhIqsxRczwSIfboCIaDBVxNW1HCj8OgijGdWGN94SGOdb8+mwRKyDJ7vlqIEs/xVDgbQG2LrNYGeEFKftR/0pTZ0JNxeMoHH/pPCtXniXgaPMye+usfgoZ+5iJEjv2mws1uRpFwwbE2zWPlohbZ9QWSPuTs4KICcWt+FzzN3Hypm97yHZPcFYZj748b5Rwh84h0baofDEoVPr/K4YY0XIeAg3GqGCOqFQk/wqaneYzc5jutDfdH8FqH2mqIfpl2HTjW8MHfwXKPu4Hxw2aUFHCZud1Z3rK+Xur8rYRNi8x0+wn8jufPPehTBNBZMR5PBpbog9aY6XHQYEyumH4=
    REDASH_COOKIE_SECRET: AgBqenc9YSB5/HktdQYeZCUCgEEhLHDzGivlLCNStcxNsw0AsE3gdzof5EOcDx71xXurjr2OggjLhQl2TjGya87ce8An63TgUCJmx1U5DSL4n5C+Tw6ZROoych7XU0p02wRSf9wZapEtizcNqeITfSPdYUymO2qSgfUfCI+mJNelXQOi2Y5cveFnJ8Q6TNuIq2pvFlzaicmpcXD5PFSvI2+pkchEGr8UYpOhVEYe7R83ypDED9D1L0t4jaul5ZVdVz04nPqPxMrTvIc+ntnZb6gLGvav3UI7T/UaN6xuXw87dAYVCyse+APYNafwgXu/RvXfT0kcRU5wtQTxT1bMQrE8DCOMrSQUvP7MRLHifspCmx02HXz0wg9l1coZVgjW5HYV2w+P+sfdnDHXxz1h2IsU1OzAR9PWUhgC3pV34lFSBH/rTDwsZV5cNWNuw3NslL8VNmktPuzDZcrXgNkWnBzcrSP/RnAZmdnMp3bC17plF2VBVUwJLDLXM6xkLRBrp+4UKl1z0LuUNt7rz5/5+hhWU5A5tgy2SxxsfT6u9AuaesH+65OgVNgJlZoNI0Y+i5yI2rIIb72UjAnuTok7TzFNqfqlVOOL6ftB/P2jJh81XSdLWuCaaGyp5cp/YXkeflTCIOwUruLUOOh7pAXjntU1v9CD8zH11gqgQIh6Mse05eH9VUTXAPTDTn5Rdyu7ZwPufYVfQvM=
    REDASH_DATABASE_URL: AgCQsjejiQh2MiTSRo7O01J6Z/jBdjXZ6ju5gtEZW9fo6nyMQOPt6v/50TrN/l+1RIGdyCAk9P1SNdyoY7Q+SdDsiGWno/Wpq8WmOXxe3ohDG/B3j33GSXtQDhSZ6z0Q3qYZ4uorAvai1fyXXNoR0sCZwJGutV4ZWBUEKZ7+1Ib2maLrei4FNQ8guQ5f17mkykzVOuoCGIOSGjsVv2QOSoS0wxjf2mdNbFd8wyqj64ovxcy2aKONLTxUQm02/w2yeuLDMnDNSefuZGXoI77zrAfS+2vhbqoP0Sae53otpWhBiZ8M4q/kvA26AHKO9TZ2gaJNRsJhnOIyjeVjj5UcbNS0rQB23j3vIGbrw4DxIsPb4v0FZ5sGOdHHWUh3KyC8bgpEZZzl94VROXh/RypuysSh/jpBbWsPMlKC8a6Qj6BuTYYkEUHJFjykHQhFhcpEfXluFgOut2ZpIRyNWMvvNfEfUF0OsWg5scxevf51Rmuuc4lEYVCTppNxW8qk/TxiIzPKQoEoNDJGt1wSusi5x1yYMiv7GFZCEZfK5siTR34gsGQsN+jg4owQrPgP3cHUdnzI38ugSBNh0hYYx/Zq3RIsTxotEUFVLv0pxxNuH5mVQA33ZJpdLfGI0SvIxdERBwQRFTV31bwXGhNY7fDyE7LKibaNWWCmmsCnwUdsYBLGtk6+G0uON5j4TBFImtlUh0hh9E9xW4BDL9FwO1JTPg/foFpmlwtTGSiM6SKYupKabLJ5BzGFq1KrpokFsg9B
    REDASH_SECRET_KEY: AgBbhDUuEUcGsecettOP8uj6F/QJq29czPk3HsHgNO9BmUYq/H/EOpfnEQQ75rutMiUhMHFt8+unUC2nkqbMh5LoKpIJONYfi99sza3MIWJHPl/mIAQhyXflXkjo2z2Rw8Ch6BxDQ8Byj5ODG1sPSvHY5LmGY7twNuCPR9rgI7fFl+x2Y588B7VgESCTim1MQtN5Xr5mawiYVZqcDAqyeTTaxV/VBP0DDRrimHpWma/3bmmGvvY18sIjLigX7Z9XaFhCmdp8dPFXr1Ul7L2NdNMI9qhtyhTkJbgZ6IzyCcE+umImVNe81N2RRYnX1zE6YGdUVvbSJ+oj1FmHQ1V1e2pGtIJpVltl+OWOyN9ToSlKrYyciDkoO60x3xfxOX8tcoWPiMc1wjLX5YAViYjucat0tXJrfrUxf8F98gtHi9gRY2wFJaN3MYbM9UJ77Q7Is1yDSrSaYJmBr12BRoU0xpGRQXsHKGKEj4dxiFDAVfKW4apHg7YQSX0qAYr0+w4lFCZM7rGGcd3i5CC7iwRqWcRv1GX4XH7KLmjhvXz043PHcL62v9xvuNHQHlLG06Uw5TNvoI5m5dPYFQ29LzoUu5DOlcznLIp+TH27Y6SwFFJO1Sf4BZGhJMj3rulAMC0dREc6nI2VViDlEoWtaip9XUUuWQyKdAWKWZvvipWVPZz5keUoONFoIzl3ohlwHHy/ywirm7Kvl9s=
status: {}
```

I place the file directly in my `charts/templates` and perform `helm dep update && helm install .`
The `SealedSecrets` object is decoded successfully:

```
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets 2019/11/23 13:42:02 Updating default/redash-secret
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets 2019/11/23 13:42:03 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"default", Name:"redash-secret", UID:"07e1b52c-0df7-11ea-9a24-42010aa40054", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"553276", FieldPath:""}): type: 'Normal' reason: 'Unsealed' SealedSecret unsealed successfully
```

I now use the following `helm` template for the `SealedSecrets` object definition:

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{.Release.Name}}-secret"
  namespace: {{ default "workable" .Values.namespace }}
spec:
  encryptedData:
{{- range $name, $value := .Values.sealedsecrets.encryptedData }}
{{indent 4 $name }}: {{ required (printf "A non-null value required for %s" $name) $value }}
{{- end }}
```

and copy/paste the above encrypted values in the corresponding nodes of my `values`.file, so here is the corresponding section of the `values.yaml` file that has to do with this `subchart`:

```yaml
redash-service:
  namespace: default
  sealedsecrets:
    encryptedData:
      POSTGRES_PASSWORD: AgAlVDwewStlSetsptIjV0/ZGp+PEt/Mtyga1mOLSGBu4X5L3F5meVYLym+3Ow4YilaXpMm7peq4MXJDk1GXmhBLugJEisN1kvlyKWLh0Gktu5fJFO0F8vFsQg7WgHWpmPnJiS3kfNyaRgfBSzo+v5b3USFYcFKcl5WmQFonQ69NgHM0BZKqOH4egC195DdfvI7SudokWfZYnZLUOU5t0U/zS5YvUPugoGycZ/dNSoKfV+/a9/+LrZsLEd5YP9s2cGJG4zr9WmEmaBPYRa50+pcbJlMkl8zhk7iq8zzQxC+kSm3wcbMK8JJ6z57tU8ghsV6HJZkWmkNBL1w39uPMD9imnwFEsFYRoMgjEHSh7s+LvoBsToZJ53+WrWhIqsxRczwSIfboCIaDBVxNW1HCj8OgijGdWGN94SGOdb8+mwRKyDJ7vlqIEs/xVDgbQG2LrNYGeEFKftR/0pTZ0JNxeMoHH/pPCtXniXgaPMye+usfgoZ+5iJEjv2mws1uRpFwwbE2zWPlohbZ9QWSPuTs4KICcWt+FzzN3Hypm97yHZPcFYZj748b5Rwh84h0baofDEoVPr/K4YY0XIeAg3GqGCOqFQk/wqaneYzc5jutDfdH8FqH2mqIfpl2HTjW8MHfwXKPu4Hxw2aUFHCZud1Z3rK+Xur8rYRNi8x0+wn8jufPPehTBNBZMR5PBpbog9aY6XHQYEyumH4=
      REDASH_COOKIE_SECRET: AgBqenc9YSB5/HktdQYeZCUCgEEhLHDzGivlLCNStcxNsw0AsE3gdzof5EOcDx71xXurjr2OggjLhQl2TjGya87ce8An63TgUCJmx1U5DSL4n5C+Tw6ZROoych7XU0p02wRSf9wZapEtizcNqeITfSPdYUymO2qSgfUfCI+mJNelXQOi2Y5cveFnJ8Q6TNuIq2pvFlzaicmpcXD5PFSvI2+pkchEGr8UYpOhVEYe7R83ypDED9D1L0t4jaul5ZVdVz04nPqPxMrTvIc+ntnZb6gLGvav3UI7T/UaN6xuXw87dAYVCyse+APYNafwgXu/RvXfT0kcRU5wtQTxT1bMQrE8DCOMrSQUvP7MRLHifspCmx02HXz0wg9l1coZVgjW5HYV2w+P+sfdnDHXxz1h2IsU1OzAR9PWUhgC3pV34lFSBH/rTDwsZV5cNWNuw3NslL8VNmktPuzDZcrXgNkWnBzcrSP/RnAZmdnMp3bC17plF2VBVUwJLDLXM6xkLRBrp+4UKl1z0LuUNt7rz5/5+hhWU5A5tgy2SxxsfT6u9AuaesH+65OgVNgJlZoNI0Y+i5yI2rIIb72UjAnuTok7TzFNqfqlVOOL6ftB/P2jJh81XSdLWuCaaGyp5cp/YXkeflTCIOwUruLUOOh7pAXjntU1v9CD8zH11gqgQIh6Mse05eH9VUTXAPTDTn5Rdyu7ZwPufYVfQvM=
      REDASH_DATABASE_URL: AgCQsjejiQh2MiTSRo7O01J6Z/jBdjXZ6ju5gtEZW9fo6nyMQOPt6v/50TrN/l+1RIGdyCAk9P1SNdyoY7Q+SdDsiGWno/Wpq8WmOXxe3ohDG/B3j33GSXtQDhSZ6z0Q3qYZ4uorAvai1fyXXNoR0sCZwJGutV4ZWBUEKZ7+1Ib2maLrei4FNQ8guQ5f17mkykzVOuoCGIOSGjsVv2QOSoS0wxjf2mdNbFd8wyqj64ovxcy2aKONLTxUQm02/w2yeuLDMnDNSefuZGXoI77zrAfS+2vhbqoP0Sae53otpWhBiZ8M4q/kvA26AHKO9TZ2gaJNRsJhnOIyjeVjj5UcbNS0rQB23j3vIGbrw4DxIsPb4v0FZ5sGOdHHWUh3KyC8bgpEZZzl94VROXh/RypuysSh/jpBbWsPMlKC8a6Qj6BuTYYkEUHJFjykHQhFhcpEfXluFgOut2ZpIRyNWMvvNfEfUF0OsWg5scxevf51Rmuuc4lEYVCTppNxW8qk/TxiIzPKQoEoNDJGt1wSusi5x1yYMiv7GFZCEZfK5siTR34gsGQsN+jg4owQrPgP3cHUdnzI38ugSBNh0hYYx/Zq3RIsTxotEUFVLv0pxxNuH5mVQA33ZJpdLfGI0SvIxdERBwQRFTV31bwXGhNY7fDyE7LKibaNWWCmmsCnwUdsYBLGtk6+G0uON5j4TBFImtlUh0hh9E9xW4BDL9FwO1JTPg/foFpmlwtTGSiM6SKYupKabLJ5BzGFq1KrpokFsg9B
      REDASH_SECRET_KEY: AgBbhDUuEUcGsecettOP8uj6F/QJq29czPk3HsHgNO9BmUYq/H/EOpfnEQQ75rutMiUhMHFt8+unUC2nkqbMh5LoKpIJONYfi99sza3MIWJHPl/mIAQhyXflXkjo2z2Rw8Ch6BxDQ8Byj5ODG1sPSvHY5LmGY7twNuCPR9rgI7fFl+x2Y588B7VgESCTim1MQtN5Xr5mawiYVZqcDAqyeTTaxV/VBP0DDRrimHpWma/3bmmGvvY18sIjLigX7Z9XaFhCmdp8dPFXr1Ul7L2NdNMI9qhtyhTkJbgZ6IzyCcE+umImVNe81N2RRYnX1zE6YGdUVvbSJ+oj1FmHQ1V1e2pGtIJpVltl+OWOyN9ToSlKrYyciDkoO60x3xfxOX8tcoWPiMc1wjLX5YAViYjucat0tXJrfrUxf8F98gtHi9gRY2wFJaN3MYbM9UJ77Q7Is1yDSrSaYJmBr12BRoU0xpGRQXsHKGKEj4dxiFDAVfKW4apHg7YQSX0qAYr0+w4lFCZM7rGGcd3i5CC7iwRqWcRv1GX4XH7KLmjhvXz043PHcL62v9xvuNHQHlLG06Uw5TNvoI5m5dPYFQ29LzoUu5DOlcznLIp+TH27Y6SwFFJO1Sf4BZGhJMj3rulAMC0dREc6nI2VViDlEoWtaip9XUUuWQyKdAWKWZvvipWVPZz5keUoONFoIzl3ohlwHHy/ywirm7Kvl9s=
  image: redash/redash
  tag: 8.0.0.b32245
  imagePullPolicy: Always
  port: 5000
  serviceType: ClusterIP
  env:
    config:
      PYTHONUNBUFFERED: '0'
      REDASH_LOG_LEVEL: 'INFO'
      REDASH_REDIS_URL: 'redis://redis:6379/0'
```

Then I perform a dry run installation and the corresponding object produced/rendered is the following:

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "wondering-albatross-secret"
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCCPoga3JSXUsw9lwy0sRAH79v6xpDTyjYAhdNSKsGxJpxAvqe/H4L7QO0bCt69kz9fMav+bXt/39R3np9+rGBJNIY/odIl4imjMEo68FSAZTGwmX5MbxK+gFpghozYgNr1YA/6/IjJlQ8+2rv+eZJ0A79mHB0H9VxbpWWSdYkte8sTXziHfHzEaHez5c77YOc67K/FAEhsuUPevTyZlInc4sugIySiB6PeXKvoUgQqg17wWH8jhoMXcFEES4xunlBdBfhhxJg1YEJRJmo6DM1c1urZBh+N2XXTeZWS93LBP8NQ7xGrlWiPLOGw5wjqeWCdGJ7rxobT3bRLb+Y9thuEzcpWLVch9MXnX+aBdbM2cksE3lxgR+JikcWb+R/SHts8ExJjHmR5IH1TLZvEqmft/F1kO3Pk4v8sYq1p4V88vuRiBM4H9mn8er/kJkvo0nf14Dg8RN8swaOsGcHjS/eqDeh3IXlWm8K0GBhUetdzpXk6RPvBBSONfQPtm5JaccRmb7/5Rr3D/QMyxQ7aKLT4cLD3wJwh6yQPgwKYCAQM/FnKcNjlDWzpTqale11UuvBO1GqEgYEbfRi3eJHiztXHJKVp8lYi5FRGrZOkGlMIy/fGDCjl9UdBD6O3OTo1XlSNhBidHxRs/Ce5VuZPk4j5Q76Mk8QoFdAmeD75sj6t4Ql8ZyLL9w38AHcxpmPq38LJssgn0mr/gpBP2tN4WGZOOiDqMDl+ftlUz04jfrpY/Q==
    REDASH_COOKIE_SECRET: AgCIBW3G2EOsGziUTsJW13KIRU+NRTZ5S6EQKZ6fwRLoeuAY8+VG8SAH8byjJdpxPgrhPn8VfJ8bQfWsb2toWH7BYw3ACuknSTtko/Tk2r8qIOjg/9pUIkmt6xKWiXBoqnz2u5d1NU2XEj7u7gqWwD6zYuoN5NfC2I3oSI0fVY9j4x+RVWJPuNKUYCyObHk4x8fkwPiFMv2M+KiV+vCaEXa7xClZkFGQ/QfKbOXji2HcSoB6bYHhlJEO7/8wtVp+mk6j8wn9Tu5B3TFM4SAqQgB2dvdWkMpEAuc+invtMPc5w0ojkX5lAeYLL2oC+fO7UFk3d5F7KRy1Mpa0b/wLhEay07sGYKfipuldJLR3srCLKRD33897llG0l6mP2op8IZZQfvV8d9JouCeRi23AlZ+uQcxKmb2HmMiqQg0VXi8yY0JJz+SbTgbM6nk0OWoYIxFDACxyCfdqFMju5pGX28oywEELhyLnFhljPp9waPJeU9hcIrp/12dhvdQYRRFfv/VJr5zPe0F6YPSyzr1/Uu+Dw63rntkLQqK0X3Lt18dappMcpswg0VkZ9lwv+F4S519Eh4znjRKpY8GzPtyhA8lh9PUOrbZRkM/VbnUJI4YutbrqX9wKRVA9a1W3pBieEShAc6kTE6BIgdh5xx9JvRLQ1MIzbLRg5/MAtC29jbLDUZS4+qLCgaipflk2R9ujyVPOBH2i07PrTTnXquTxvkIIKiF6XzKqs14LQs92ZERxGQ==
    REDASH_DATABASE_URL: AgB1Amo8pJBbwyVHBCCZuaobrxoJEpJPqTlljZTqmMcGCvsQQUczKx2aHDrkhdb8XoKpmMdW5Moq8uRORrjQFOD9Tr53IKq2rvuqVVQYE3d7Zgp3rKvxlup8pgdIurXwhOU96zRG6PKXwNiiY2EyUTxfzF4dfX+eje2vSjdSr8JRyVxEIK/XQt30bLbiurHBTIUqoH+ZdekcRcBZgsTd7WvTDiWf1PqxypoOrFP5FVx/PsHKNwwHoGeph4DTUU1BfzIBqOzb6TDEbkXVfrEa1y3LnrzA0wRodc0c9eJ2nr5/ABQoWEAUbHwI9z+UqdJYVFqvxOJzwO7GZ1aIce1IMreQbSYV5zZCA2qftWbhHdpr9juW8RQe7ITXWQq+ypLinv3pI84U3VllRD23naAwg2+fxzeKxsl7++g+zXTmR0q1t+WXlM5WkYkjwjRfHsUMEEgX2fZ0FB0VzIULU2K8eJOPIQJ4ZlhZck4SBp4zNO8hsOShzGWODQwdYJ8npAElqgw2BkDvmShLlTyIOBiU0BXRw0yHnPFuE8y2R0bXO9EbdyKLAj3sd1v+Tc3XMM6A6lENInk2PeULUfnl1bvPq1GjPVMnhgIrpD53+QK5iqVlyflwqG+NyIL9lp6LwzEW9XOCIP/CZlKO4d9uTuDktThW8BmVYQz6WQ74/FUa7V+z2HsI9Bot9cUloXeeuwQ9n78wMF5EKgDvq6eHkvbaWYv5+D30foGnB19dekxHtzoAHrpfqpfU4P/lt0ggW1yk5cYTQ3cRj5BvDSvC1PWkMpgsNTpAAQwoHXc=
    REDASH_SECRET_KEY: AgA8poD9jTqDyPBbZOkdCr47HywFnQaXs99VAf9BqRyaVaXB0wuQpGjutKXcWPJuCH5RUzAhtkwAfTma1EFMEM4CK77CctMyGQsf0LvG29IswUQe29Ye/DeE4I+mOi520CNgz7OtdF23x6UbY5GZSmp82Muy+MMz6xBwW5JBGsZzggujAqbAlnzLAdrAfKP3tfYknCYmktZEpBqwi/liDFyMGxAZ+sxM5QBtCOxuJoJtoYabujTDqiFVlTKa/uLUTwgEspuSDr8eyoYS8xv89wKHvsXjsqF+XMhiMVqOSEfa2I4Ulr5kRq8XOhdFgXVA2OCRfkGBOLXz6Kp673MAa5mkCN2206NVZRGwIyCT6/DFqOym/vykRDm3vH95babN5HeC3S6j6Fz+QVVh1wrFnZ2FOLQwpUemqQPfOYvcG81XDSoJ6m1RIOqrbgl2I46ftX44F3i/mEZDYGcB1UeVljxLCRKxrf3GgGEQgs69wqCImfV1OziZlAVZHHsMhc3JsGgENRnkdupRrkYGp58oVG+O3OtXP0nScadeTNmRlJaK0wNES6JQN5nqB0DCJcdk/0S+jCAeHrhlyLHaTa+MMrwXMNtLGiTo8ts7WOl54pxGtCiwMdN6ysA1Kz0hbwUuoJugKw//8cTgy1p3s1D94yD5CF8D4JEYsvOIrY8/HD8s1bxj/+Bw6CWhiFWGVTrm4j7BwgCSmKHHOpU+nfQc0tfFThXP0GVJ8heof8MRvSA/gw==
```

Then I proceed with the actual installation (after completely deleting the previous `helm` release. The `SealedSecret` object now fails to decrypt

```
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets 2019/11/23 13:51:41 Updating default/anxious-wolverine-secret
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets 2019/11/23 13:51:41 Error updating default/anxious-wolverine-secret, giving up: no key could decrypt secret
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets 2019/11/23 13:51:41 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"default", Name:"anxious-wolverine-secret", UID:"60e02197-0df8-11ea-9a24-42010aa40054", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"555410", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret
redash-sealedsecret-release-sealed-secrets-d5996f677-5drtp redash-sealedsecret-release-sealed-secrets E1123 13:51:41.957718       1 controller.go:194] no key could decrypt secret
```
