### ISSUE TITLE
Should not add namespace when sealing "cluster-wide" secret

### ISSUE THREAD

**Issue by sfitts** [bitnami-labs/sealed-secrets#323]
When sealing the following secret:

```
apiVersion: v1
data:
  password: <elided>
  username: <elided>
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: keycloak
type: Opaque
```

The resulting SealedSecret resource has the namespace set to "default".   

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: keycloak
  namespace: default
spec:
  encryptedData:
  password: <elided>
  username: <elided>
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: keycloak
      namespace: default
    type: Opaque
status: {}
```

This makes it harder to use across namespaces as desired.  Seems like in this case the resulting SealedSecret should have no namespace added.

**Comment by mkmik** [comment]
GH misparsed a natural language sentence as a directive to close the issue 🤦‍♂

**Comment by mkmik** [comment]
#328 contains the actual fix that would close the issue

**Comment by shirkevich** [comment]
Still facing this bug in cluster-wide mode on latest 0.12.1. 

When applying following SealedSecret:

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: test
spec:
  encryptedData:
    foo: AgCofqA2HQwUfBTmgz4Jqb2V+jBRqJfjAQdjCCa220PcnHv50rH0nK8XKm2tqW01qVSkw8q4tY+ar5KJ41hmtNEBy86g5tgK0hgU6vDjqOvMY7ribuf7y68TEfcNeA3bIph4M7zhhGu74laK6z70me8bCFbA9Z0uwWVjPzLUP7JcPDs3/qNrxQqmwBm81le1/qjjCm29IokaykO0FhZQfgnXaKaBGYJIA+wjdATWY9ZYPZtDXWDOQ2GdBTMUsUT1wYyq8uSs7i7wTUNkG4yUcwkrNIzn95sBwR9c9VE1wmtJShm1D3+KMnUY3ayVUfllXT33XOLfI1yhrisVP1RBurMTAfHB56W1y6+23/Cq0aA0C49d7yR9XmhwxNUVXVihtQMKFwcPdCOyulBN3sbP4S9EOGVrwBTVPRU8g9XlUaWUZ/XuWZwy6l8anRyne7PQ9yb4Nw6GXqfu4HxTNGLu6iqJqbNNxlYbTRJOArhhosqHhrXzorfIJyl9FYZzTqYBwUl+TymMbHFtl8YYJ8/OaSOoYGxgTiQr7gFTA3zEJHNNUwGq6/Uo54YsZdhwJoNXEJxrz7QXMWgxWdmdSUta0r6RCwHb6Ts0yl+f3G7xBUUPD0xtgPe/r3TtkDXxK0dO/wd1Jfi5pTXaemC1GOPvx2ZyVr6XYh5u8tM+TbcWngzbyodAC0al4B0TsSb12V6sHxGJdAI=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: test
    type: Opaque
```

I'm getting Secret with default namespace provided: 
```
apiVersion: v1
data:
  foo: YmFy
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: "2020-05-04T11:49:54Z"
  name: test
  namespace: default
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: test
    uid: 420c25da-55c7-4253-8e2b-05a57ee9ff13
  resourceVersion: "6654731"
  selfLink: /api/v1/namespaces/default/secrets/test
  uid: d2af2acd-adb4-4e52-9e45-fe646653aeae
type: Opaque
```

In my case I need it with `type: kubernetes.io/dockerconfigjson` but even Opaque is not working.
