### ISSUE TITLE
kubeseal controller shows "giving up: no key could decrypt secret" but deploys the secret anyway

### ISSUE THREAD

**Issue by sfxworks** [bitnami-labs/sealed-secrets#342]
Testing out kubeseal.

Deployed the helmchart 1.6.1. Was able to get the cert just fine. 

```
kubectl create secret generic mysql --dry-run --from-literal=ROOT_PASSWORD=my-root-password --namespace wdev -o json | kubeseal -o yaml > .\secret.yaml
```

```
2020/01/12 23:49:23 Error updating wdev/mysql, giving up: no key could decrypt secret (ROOT_PASSWORD)
2020/01/12 23:49:23 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"wdev", Name:"mysql", UID:"6ff7d9d6-fb69-40a8-87a3-00582e748f34", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"17107584", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret (ROOT_PASSWORD)
E0112 23:49:23.056086       1 controller.go:194] no key could decrypt secret (ROOT_PASSWORD)
```

After deployment, the controller shows it could not decrypt the secret. Following the concept of scopes, https://github.com/bitnami-labs/sealed-secrets#scopes I deleted the empty secret and the kubeseal secret, made the namespace and switched context to that namespace. Then, I deployed the kubeseal secret again. I got the same error in the logs, but this time with the secret populated with the correct data.

It looks like everything went ok. The logs seem to show otherwise so I am a bit confused here.

**Comment by pramodramdas** [comment]
Hi, I am also having same issue. Because "SealedSecret" is not decrypted and deployment is not successful.

**Comment by mkmik** [comment]
@sfxworks; so you're saying that after you learned about scopes and took care of using the right namespaces it works fine except you're confused that you see some errors in the logs?

@pramodramdas: did you also read about and understood scopes, but it still doesn't work for you?

**Comment by pramodramdas** [comment]
@mkmik, My namespace of kubernetes GCP is "default" and namespace in SealedSecret is also "default".
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-env-secrets
  namespace: default
spec:
  encryptedData:
    FORGOT_PASSWORD_SECRET: AgAlPchGpjvg/ZnTwofPhssiSoub//mvqYozgXXkaI6.....
    JWT_SECRET: AgC9xJLExHHu8QjSVPcNoF....
  template:
    metadata:
      creationTimestamp: null
      name: user-env-secrets
      namespace: default
    type: Opaque
status: {}
```

**Comment by pramodramdas** [comment]
But i noticed that `kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.9.8/controller.yaml `
deploys sealed-secret controller to "kube-system" namespace

**Comment by mkmik** [comment]
The controller installs in the kube-system namespace. That's ok.

Can you show me the exact commands you used to create the sealed secrets file and the command you have used to apply the file to your cluster?

**Comment by pramodramdas** [comment]
@mkmik `kubeseal --format yaml < test-env-secrets.yml > test-env-sealed-secrets.yaml`
`kubectl apply -f k8s/`
I have all files inside k8 folder and this commands work fine in my local ie. minikube

**Comment by mkmik** [comment]
how did you produce `test-env-secrets.yml`?

can you share the non-secret part of `test-env-secrets.yml` (in particular the `metadata:` part).

also can you please show the `metadata:` section of the resulting `test-env-sealed-secrets.yaml` file?

**Comment by pramodramdas** [comment]
@mkmik 
```
apiVersion: v1
kind: Secret
metadata:
  name: test-env-secrets
type: Opaque
data:
  JWT_TOKEN_SECRET: xxxxxxxxxxxxxxxx
```
output:
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-env-secrets
  namespace: default
spec:
  encryptedData:
    JWT_TOKEN_SECRET: AgDl0ghpaXsHjUKO/Jpq6XewnfTQb+kZ............................
  template:
    metadata:
      creationTimestamp: null
      name: test-env-secrets
      namespace: default
    type: Opaque
status: {}
```
