### ISSUE TITLE
Unknown flag: --key-renewal-period

### ISSUE THREAD

**Issue by cprovencher** [bitnami-labs/sealed-secrets#370]
Docs aren't clear that --key-renewal-period is not an argument for the kubeseal CLI.
It should mention it's supposed to be used as an argument in the controller deployment.

**Comment by mkmik** [comment]
fixed, thanks

**Comment by milles9393** [comment]
@cprovencher Do you mean something like this

```
 spec:
      containers:
      - args:
        - --key-prefix
        - sealed-secrets-key
        - --key-renew-period=0
        command:
        - controller
```
