### ISSUE TITLE
kubseal --raw and types

### ISSUE THREAD

**Issue by remmeier** [bitnami-labs/sealed-secrets#372]
I attempted to seal a secret for a dockerconfigjson-typed secret:

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: registry-cred
spec:
  encryptedData:
    .dockerconfigjson: ...
  template:
    type: kubernetes.io/dockerconfigjson
```

from the controller I got:

```
type: 'Warning' reason: 'ErrUpdateFailed' Secret "sb4b-registry-cred" is invalid: data[.dockerconfigjson
]: Invalid value: "<secret contents redacted>": invalid character 'e' looking for beginning of value
```

After trying around for a while I noticed that the secret can be unsealed if I remove `type: kubernetes.io/dockerconfigjson`. It also worked when I do not make use of  `--raw` but rather seal the complete secret.

So I assume the type is used as criteria for the sealing? I did not see a command line parameter to pass the type with raw. Or I may missed something?
