### ISSUE TITLE
help: first install, "no key could decrypt secret"

### ISSUE THREAD

**Issue by ghostsquad** [bitnami-labs/sealed-secrets#378]
I just installed the SealedSecrets controller, and deployed my first sealed secret, but was met with the following log:

```
E0320 22:47:43.536752       1 controller.go:194] no key could decrypt secret (<REDACTED>,<REDACTED>)
2020/03/20 22:47:43 Event(v1.ObjectReference{Kind:"SealedSecret", Namespace:"example-namespace", Name:"example-742c4e8960ef", UID:"cf0dc2e8-6afc-11ea-ba11-029ce250dc74", APIVersion:"bitnami.com/v1alpha1", ResourceVersion:"213023291", FieldPath:""}): type: 'Warning' reason: 'ErrUnsealFailed' Failed to unseal: no key could decrypt secret (<REDACTED>,<REDACTED>)
```

controller version: `0.9.8`
kubeseal version: `0.9.8`

sealed secret value:

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-742c4e8960ef
  namespace: example-namespace
spec:
  encryptedData:
    <REDACTED>: <REDACTED>
    <REDACTED>: <REDACTED>
  template:
    metadata:
      name: example-742c4e8960ef
      namespace: example-namespace
```

I'm not sure how to debug this.
