### ISSUE TITLE
Not getting secret on different namespaces

### ISSUE THREAD

**Issue by k8s-learner** [bitnami-labs/sealed-secrets#406]
below is my Secret.yaml

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-variable
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
type: Opaque
stringData:
    MGMT_SECRET: "wsdsds3joS4HgFcb"
data:    
    rabbitmq-password: "test@123"
```
MGMT_SECRET is required in default namespace and rabbitmq-password is required in rabbitmq namespace. I have used this annotation.

`sealedsecrets.bitnami.com/cluster-wide: "true"`

I am getting the values in default namespace but not in rabbitmq namespace. I had this understanding that if I use  `sealedsecrets.bitnami.com/cluster-wide: "true"` then it's should be available to all namespaces.
