### ISSUE TITLE
Secret annotations lost during kubeseal

### ISSUE THREAD

**Issue by chrisjholly** [bitnami-labs/sealed-secrets#410]
I have a secret for a database that I would like to encrypt. The difference being it is also a Helm Hook (pre-install) to create a new user for the database.

e.g

```
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "10"
  name: 'some-database-secret'
data:
  database.password: dGVzdAo=
  database.username: dGVzdAo=
stringData: {}
type: Opaque
```

---
Below is the kubeseal command and encrypted secret (v0.12.1)

```./kubeseal --controller-namespace=fluxcd --controller-name=sealed-secrets-controller --scope=namespace-wide --format=yaml < db-secret.yaml```

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: 'some-database-secret'
spec:
  encryptedData:
    database.password: <some-encrypted-value>
    database.username: <some-encrypted-value>
  template:
    metadata:
      annotations:
        helm.sh/hook: pre-install,pre-upgrade
        helm.sh/hook-weight: "10"
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: 'some-database-secret'
    type: Opaque
```

The problem is that the annotations that are on the Secret are part of the helm lifecycle and are not respected when on the SealedSecret resource. Is there a workaround for this?
