### ISSUE TITLE
Errors updating sealedsecret status

### ISSUE THREAD

**Issue by dad264** [bitnami-labs/sealed-secrets#417]
We were getting a ton of messages like this:

Error updating SealedSecret testing/test-secret status: sealedsecrets.bitnami.com "test-secret" is forbidden: User "system:serviceaccount:kube-system:sealed-secrets-controller" cannot update resource "sealedsecrets" in API group "bitnami.com" in the namespace "testing"

To fix it, I added the `update` permission to the clusterrole `secrets-unsealer`

```yaml
 - apiGroups:
   - bitnami.com
   resources:
   - sealedsecrets
   verbs:
   - get
   - list
   - watch
   - update
```

Was that the right thing to do? Should we get it added to the helmchart?
