### ISSUE TITLE
[SealedSecrets + Helm] Race condition possible while unsealing?

### ISSUE THREAD

**Issue by jebreuer** [bitnami-labs/sealed-secrets#428]
Hi all!

In my scenario I use Helm to deploy/update a microservice. I used to use plain k8s Secrets for passing in credentials to my service. I am in the process of switching to SealedSecrets to replace the aforementioned Secret.

What I already implemented is the following:
1. use a Helm hook (`pre-install,pre-upgrade`, weight 3) to deploy a dummy Secret with the `sealedsecrets.bitnami.com/managed: "true"` annotation
1. use a Helm hook (`pre-install,pre-upgrade`, weight 4) to deploy the actual SealedSecret
1. roll/update the Deployment of the microservice if the sha256sum for the SealedSecret has changed (using the sha256sum as an annotation in the Deployment resource)

My question is whether the creation/update of the SealedSecret with the corresponding unsealing process is an synchronous operation, e.g. will the `kubectl apply -f mysealedsecret.yaml` only return when the SealedSecret is already unsealed and the corresponding Secret is created?

My concern is that in the example above it could happen that the Deployment of my microservice is already rolling because of the changed sha256sum in the Deployment but the sealed-secrets-controller hasn't unsealed and updated the secret yet resulting in a deployment that doesn't use the latest secret data.

I am fairly new if it comes to k8s and the surrounding ecosystems so feel free to drop anything that could help me better understand what is going on here.

Many thanks & kind regards
Jens

**Comment by lsoica** [comment]
As helm is the standard package manager for k8s, I assume this use case is pretty common.
Is it covered by sealed-secrets ? Is there a recommended pattern for it ?
Thanks!

**Comment by uhinze** [comment]
I think this is particularly important when the secret is used in environment variables, as those cannot change once the pod has started (vs. secret mounted as file). 
Also, I don't this is a Helm-specific issue, the question is more general about the synchronicity.

As there has been no answer so far, I've created a minimal example to test the behavior:

```
apiVersion: v1
data:
  foo: YmF6 # "baz"
kind: Secret
metadata:
  name: test
  annotations:
    sealedsecrets.bitnami.com/managed: 'true'

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test
  namespace: default
spec:
  encryptedData:
    # "bar"
    foo: AgCBNrM14CN0oz9e5r92rUvRKy8Jmng3crwr0V3rqjs3MlTFg6EX1dKbvTRBTADwVWsAiH2Yy/tpq85LYBcQx6kOTFx2Ith7lvjYq1fBfrrKjBxJELEhB8vsIP2t8doZbmipDVXyOCTv3x3pLRqtHm8S2jEhWhLR5HDqxmh0kF8Xaks9pb1dkpJJAd94M0TyTSk8f7RjOKuApQxqTWAl2sZoQ76s1gbHuDsrhIelv9c1JQxGkkBfB1eE6jRsMC6QK9jmfgsuWkghJQN3nR66z4U5V89sPhVJ0X95v+lmRpeO64Q5ohihJ3LyzbkjXHPveR6ScvKWytG7ISKj4HbrvVRLQAyBKmqNkMxory7aseo66ts4ERyTejWdd9jKRvJfvJxVUTketRO4lkSWyT12+eTTQFt6sBWyIDPEgtb2CmaQT3z2v5F02oxiBtStzEPLE7B3kQMFW6sF8yQvwKLA4tz5jUR2PBh3qXdnQSP+EEcx1Wz0uPqOy+6YuDNak4GnWyoLpR36+Cpm+OeT9RxLuvuCNlVehveGpX1pEOO74yu9i90TCm7/o7U7wFChLJZNt7Sg5ANY9wK87HFtg0EvcCkjNABeXsFa7FIqteNBiqMsLAePZL0y1rSFNO/jRTSWAY4csqKLxysWPuMo+3r7ON8iZGNPBNfOsvCkR4TB0I4ifXCn2RbUwyTZie35tzaplCxz9cM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: test
      namespace: default

---

apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: web
      image: nginx
      env:
        - name: FOO
          valueFrom:
            secretKeyRef:
              name: test
              key: foo
```

This creates a secret, then a SealedSecret overwriting the initial secret, and then a pod that uses the secret.

After applying this, I exec'd into the container and `echo $FOO` -> it returned `bar`. So that's good, as that means the secret was updated by the SealedSecret before the container started.

If that means that SealedSecrets works synchronously I still cannot tell. Could also be that it's just faster that the scheduling of the pod or so. But in either case, it seems fine to use that way.
