### ISSUE TITLE
no key could decrypt secret

### ISSUE THREAD

**Issue by lukesterg** [bitnami-labs/sealed-secrets#443]
**Issue**
The sealed-secrets controller continuously logs "no key could decrypt secret" after deploying.

**Steps to create**
Starting base is a working cluster in Helm using opaque keys.

1. Installed Sealed Secrets as described in installation and also followed https://github.com/bitnami-labs/sealed-secrets/blob/master/docs/GKE.md.
1. Copied public certificate from log and confirmed the cert matches using `kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml | grep tls.crt | awk -F ' ' '{ print $2 }' | base64 -d`.
1. Tried encrpyting keys using the following methods (with an without local certs):
`kubeseal -cert=cert.pem --raw --scope cluster-wide --from-file <file>`
`echo -n <key> | kubeseal --cert=cert.pem --raw --scope cluster-wide --from-file=/dev/stdin`
1. Generated new k8s yaml file (instead of Helm) and used `kubeseal < <file>` and then copied and pasted keys.
1. Deleted secrets from sealed-secrets and re-spawned the controller to generate new keys. Re-encrypted all keys, but got the same result.

**Example of generated file**
```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rest-sandbox-product-rest-environment
spec:
  encryptedData:
    awsAccessKey: *REMOVED ENCRYPTED DATA*
    questKey: *REMOVED ENCRYPTED DATA*
  template:
    metadata:
      name: rest-sandbox-product-rest-environment
      labels:
        helm.sh/chart: product-rest-0.0.1
        app.kubernetes.io/name: product-rest
        app.kubernetes.io/instance: rest-sandbox
        app.kubernetes.io/managed-by: Helm
```

**Logs**
no key could decrypt secret (rest-service-account.json)
giving up: no key could decrypt secret (rest-service-account.json)
will retry: no key could decrypt secret (rest-service-account.json)
Repeatedly.

**Environment**
Kubeseal v0.12.5
Kubeseal server v0.12.5 installed in kube-system
Private GKE cluster and followed https://github.com/bitnami-labs/sealed-secrets/blob/master/docs/GKE.md
Helm
