### ISSUE TITLE
Create sealed custom resources

### ISSUE THREAD

**Issue by mruoss** [bitnami-labs/sealed-secrets#444]
This is a proposal for an enhancement. It would be nice if a sealed secret could be unsealed not only into resources of `kind: secret` but into any custom resource. This way a custom operator could take care of the unsealed resources. What do you think? 

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: mynamespace
spec:
  apiVersion: v1
  kind: CustomResourceUserPassword
  encryptedData:
    foo: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....
```
The controller would unseal that into something like:

```yaml
apiVersion: v1
kind: CustomResourceUserPassword
metadata:
  name: mysecret
  namespace: mynamespace
data:
  foo: bar  # <- base64 encoded "bar"
```
