### ISSUE TITLE
add ability to template arbitrary data keys within resulting secrets

### ISSUE THREAD

**Issue by evq** [bitnami-labs/sealed-secrets#445]
sometimes when deploying services on k8s you end up needing to [create a secret which contains a entire config file.](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/alerting.md) in such cases you often only have a small amount of data that is actually secret, the rest of the config file could be safely kept in plaintext. in such cases `sealed-secrets` could offer a large usability win by allowing arbitrary keys within the resulting secrets to be created from a plaintext template which uses the decrypted data keys as inputs. 

`sealed-secrets` already has the concept of secret "templating", perhaps a `TemplatedData` field could be added to the `SecretTemplateSpec` to enable this.

---
**Example** (extended from the README):
```
--- 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata: 
  annotation: 
    kubectl.kubernetes.io/last-applied-configuration: "...."
  name: mysecret
  namespace: mynamespace
spec: 
  encryptedData: 
    dockerAuth: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....
  template: 
    metadata: 
      annotations: 
        jenkins.io/credentials-description: "credentials from Kubernetes"
      labels: 
        jenkins.io/credentials-type: usernamePassword
    templatedData: 
      .dockercfg: |-
          {
            "auths": {
              "https://index.docker.io/v1/": {
                "auth": "{{index .Data "dockerAuth"}}"
              }
            },
            "HttpHeaders": {
              "User-Agent": "Docker-Client/19.03.9-ce (linux)"
            }
          }
```
would result in a secret like:
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: mynamespace
  labels:
    "jenkins.io/credentials-type": usernamePassword
  annotations:
    "jenkins.io/credentials-description": credentials from Kubernetes
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: mysecret
    uid: 5caff6a0-c9ac-11e9-881e-42010aac003e
type: kubernetes.io/dockercfg
data:
  dockerAuth: ewogICJjcmVk...
  .dockercfg: ewoJImF1dGh...
```

where the decoded `.dockercfg` looks like:
```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "hello world..."
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/19.03.9-ce (linux)"
	}
}
```

**Comment by musabmasood** [comment]
+1

We have a similar usecase with ArgoCD, the cluster secret should look like this:

```
apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster.com
  server: https://mycluster.com
  config: |
    {
      "bearerToken": "<authentication token>",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "<base64 encoded certificate>"
      }
    }
``` 

In the secret above, `name` and `server` are not really secrets and I don't want the devs to encrypt them uselessly. So there is no way for me to create a `SealedSecret` from it with just the `bearerToken` and `caData` that should be encrypted.

A simple solution that SS could be implement is to support `data` key, which can take the usual b64 values:

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: myns
spec:
  encryptedData:
    foo: <ss-encoded-value>
  data:
    bar: <regular-b64-encoded-value>
```
