### ISSUE TITLE
Status not updating despite --update-status

### ISSUE THREAD

**Issue by TrueBrain** [bitnami-labs/sealed-secrets#555]
First of all, I know very little about how CRDs etc work, so take the following with a salt of grain.
Running k3os with `GitVersion:"v1.19.5+k3s2"`.

When I enable `--update-status`, my SealedSecret objects still weren't getting the `Status` field. I checked everything as in:
- Checked the Go-code was really updating the status: it was
- Checked the argument was really set: it was
- Checked that the status update was send: it was (I revoked the permission, and it was giving an error)
- Checked k3s (which I am using) doesn't magically not support subresources or something: that was not the issue.

In the end, by looking how others did it (longhorn in my case), I found that the `openAPIV3Schema` doesn't set the magic `x-kubernetes-preserve-unknown-fields` to true for `status`. After doing this, it magically works!

```
      openAPIV3Schema:
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
```

I have no clue why this would be the case etc etc, and I am sure you guys will know a lot better what is going on here, but without that addition, I cannot get this to work at all.

Am I right that the schema definition is wrong, or am I just doing something else wrong?

Tnx!

**Comment by jsoref** [comment]
Thanks, applying this change fixes it for our ArgoCD-helm managed sealed-secrets deployments.

**Comment by dbyron0** [comment]
This helped me, so perhaps it'll help others too: https://github.com/argoproj/argo-rollouts/pull/1044#issuecomment-806235802

**Comment by iamnoah** [comment]
kustomize patch if anyone else needs this before the PR is merged and released:

```yaml
# makes --update-status work: https://github.com/bitnami-labs/sealed-secrets/issues/555
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
spec:
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```
