### ISSUE TITLE
Question: Where do I remove the key renewal?

### ISSUE THREAD

**Issue by milles9393** [bitnami-labs/sealed-secrets#565]
Where do I apply necessary configuration to remove the key renewal? It stated in the docs, not sure if I am completely lost or just bad..

Is is in the controller deployment?

```
spec:
      containers:
      - args:
        - --key-prefix
        - sealed-secrets-key
        - --key-renew-period=0
        command:
        - controller
```  

From docs, 
``` The renewal time of 30d is a reasonable default, but it can be tweaked as needed with the --key-renew-period=<value> flag for the command in the pod template of the sealed secret controller. The value field can be given as golang duration flag (eg: 720h30m). ```
