### ISSUE TITLE
[helm chart] cannot inject imagePullsecrets for private registry

### ISSUE THREAD

**Issue by abdennour** [bitnami-labs/sealed-secrets#594]
`.Values.imagePullsecrets` is needed .

This is needed for private registry case (.i.e quay.io is proxied thru a private corporate registry)

**Comment by arthurbdiniz** [comment]
```
image:
  repository: quay.io/bitnami/sealed-secrets-controller
  tag: v0.16.0
  pullPolicy: IfNotPresent
  pullSecret: ""
  ```
