### ISSUE TITLE
Failure to resolve bad Synced status after it's fixed

### ISSUE THREAD

**Issue by cjyar** [bitnami-labs/sealed-secrets#603]
We created a Secret `backup-db-simple-crypt-key`, and then a corresponding SealedSecret. The SealedSecret was correctly annotated with:

```yaml
status:
  conditions:
  - lastTransitionTime: "2021-06-11T21:39:06Z"
    lastUpdateTime: "2021-06-11T21:39:06Z"
    message: 'failed update: Resource "backup-db-simple-crypt-key" already exists
      and is not managed by SealedSecret'
    status: "False"
    type: Synced
  observedGeneration: 2
```

Then we deleted the blocking Secret and restarted sealed-secrets-controller. It correctly created a new Secret from the SealedSecret, but it didn't remove the status. As a result, our health checks (via ArgoCD) are failing even though everything is actually fine.

We're running sealed-secrets-controller with `args: [ "--update-status" ]`.
