### ISSUE TITLE
Is it possible to install / upgrade kind SealedSecret through Helm Chart?

### ISSUE THREAD

**Issue by albertsebastian1** [bitnami-labs/sealed-secrets#607]
For example I have a Helm Chart template for SealedSecret with Key values which varies its key with namespaces. Can I install/upgrade the sealed secret via helm upgrade --install instead of kubectl apply -f <sealed-secret.yaml>

**Comment by SteelWorkerUnion** [comment]
Hey albertsebastian1, what I did to solve this type of issue was to add sealed secrets as dependencies to a helm repo this way it allows me to deploy my own templates folder which has my keys in it.

Example of my chart.yaml


```
apiVersion: v2
name: sealed-secrets-job
description:  Our secret keys helm chart
version: 1.16.1
dependencies:
  - name: sealed-secrets
    version: 1.16.1
    repository: https://bitnami-labs.github.io/sealed-secrets 
```

Then I can deploy this chart instead, hope this answers your question.
