### ISSUE TITLE
error: cannot fetch certificate: services "sealed-secrets-controller" not found

### ISSUE THREAD

**Issue by Jille** [bitnami-labs/sealed-secrets#626]
```
$ ./kubeseal --version
kubeseal version: v0.16.1-0.20210512081140-62cfb264f53e
$ ./kubeseal --controller-namespace kubeseal --fetch-cert
error: cannot fetch certificate: services "sealed-secrets-controller" not found
```

Adding `--controller-name=sealed-secrets` seems to solve it, but it seems strange this doesn't work out of the box.

I installed the Helm chart through ArgoCD:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
    helm:
      releaseName: sealed-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeseal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```
