### ISSUE TITLE
Missing YAML document start "---"

### ISSUE THREAD

**Issue by agrrh** [bitnami-labs/sealed-secrets#645]
Currently, `kubeseal` generates yaml file with absence of document start sign:

```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: mynamespace
spec:
  encryptedData:
    foo: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq.....
```

Thus, `yamllint` in strict mode can't succeed:
```
$ yamllint --strict -c .yamllint.yml ./
./example/my.sealedsecret.yml
  1:1       warning  missing document start "---"  (document-start)
```

We may suppress this, but it seems more convenient to apply proper template to yaml generation.
