### ISSUE TITLE
Injecting secrets into config file templates - Config Template is folded to a oneliner

### ISSUE THREAD

**Issue by Brice187** [bitnami-labs/sealed-secrets#660]
My well formed secret:

```yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: example-conf-secret
  namespace: example-namespace
spec:
  encryptedData:
    upload_pass: ""
  template:
    metadata:
      name: example-conf-secret
      namespace: example-namespace
    data:
      example.conf: |
        ##############################################################################
        # Security config

        # After start, change to this user/group. Make sure they exist!
        user = example-daemon
        group = example

        ##############################################################################
        # Example config part1

        feed_name	= "example"

        # The URL, ##DATE## will be replaced with the current date
        fetch_url	= "https://example.com/##DATE##.zip"

        # start the next fetch at 01:xx (they files appear around 00:15 UTC)
        fetch_hour	= 3

        # Use the NC line, as the normal route seems to be very slow
        proxy		= "http://proxy:1234"

        # Check the input archives going back so many days.
        last_days	= 9

        # Archive so many percent of all samples instead of uploading them into MWScan
        # Not yet implemented for daily feeds, see ticket #1988
        #archive_percent = 0

        # Archives are protected with that password
        archive_pwd     = "trivial"

        # Reject samples that are smaller than so many bytes, 0 to disable
        min_size        = 32

        # Reject samples that are larger than so many bytes, 0 to disable
        max_size        = 0

        # Archives are not GPG encrypted
        no_gpg         = 1

        ##############################################################################
        # example config part2 

        upload_pass	= {{ index . "upload_pass" }}
        upload_user	= "example"

        # EOF

```

When I inject my secret with:

```
echo -n supersecretpassword | kubectl create secret generic example --dry-run=client  --from-file=upload_pass=/dev/stdin -o json | kubeseal --cert example.pem -o yaml -n example-namespace --merge-into example-sealed-secret.yaml
```
The resulting yaml is:

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: example-conf-secret
  namespace: example-namespace
spec:
  encryptedData:
    upload_pass: AgAnlYnafNWUaO4u2Oh6nm5tasl7ywEIUOiFxE7/4yv9WpWdczqz0JkP1WhrUSddvngt5NzL8ggbcRDA4zPXitXlPO8W97mghf+Q6kprQKCFpT75dQqYE1leZ6cZkoQP/1oZMtn4+QEKSi+32XEyLhJk36qTqec8OjcZ1V0EdxriUEng8AM0sWHP7FVnGu+mqen/iW4DfGonHeMJ7OHpeiY63OnIcxkgfxf7posUFe6BaW6G6CVaiLOyyYssxRZD8WUOvXRf+YlzMzBr7CY8wmuvM6BdBvgNLGCQDdKSuXjC3NJHPFTN+9a7PQiMYt3eM519z7GIGvn93wRpVWDmOCiiNRpWSfLt+W41ay7Ob5KyGKTt0DmCaoMhltdqJ6+pii+XKjBqp8TsCt/CoqspyKN2mtbPFhO1n9TjrWI8NNfoaWWnaOoHuzK+jjzDGkUz5mJRO/Tz2R00jXq10xwACNQpgZNBd1+q2Ss+Y0lDb91e4f4IZc7/QEI2a/EoUo/IseYNvu9WRXaEawL1Ss4hFzIcW41dK3M9/z/PcVQGY8oIv1aa6IabJl0O+v7uIeILcfEj492xXweBQGOn1TeIeVbGjBIIzldjqjz8yLT8zjmf5yvICtun72zxxJPy2wiShYCfST+9gS1Njzqu4h3kER9njEbdoNAW9w8O8+K24rdB1WaAOY8X5Xt+YJtl1d9j5Q75JKxSJFfwurOHM35jQOWQRw+1
  template:
    data:
      example.conf: "##############################################################################\n# Security config\n\n# After start, change to this user/group. Make sure they exist!\nuser = example-daemon\ngroup = example\n\n##############################################################################\n# Example config part1\n\nfeed_name\t= \"example\"\n\n# The URL, ##DATE## will be replaced with the current date\nfetch_url\t= \"https://example.com/##DATE##.zip\"\n\n# start the next fetch at 01:xx (they files appear around 00:15 UTC)\nfetch_hour\t= 3\n\n# Use the NC line, as the normal route seems to be very slow\nproxy\t\t= \"http://proxy:1234\"\n\n# Check the input archives going back so many days.\nlast_days\t= 9\n\n# Archive so many percent of all samples instead of uploading them into MWScan\n# Not yet implemented for daily feeds, see ticket #1988\n#archive_percent = 0\n\n# Archives are protected with that password\narchive_pwd     = \"trivial\"\n\n# Reject samples that are smaller than so many bytes, 0 to disable\nmin_size        = 32\n\n# Reject samples that are larger than so many bytes, 0 to disable\nmax_size        = 0\n\n# Archives are not GPG encrypted\nno_gpg         = 1\n\n##############################################################################\n# example config part2 \n\nupload_pass\t= {{ index . \"upload_pass\" }}\nupload_user\t= \"example\"\n\n# EOF\n"
    metadata:
      creationTimestamp: null
      name: example-conf-secret
      namespace: example-namespace
```

This is not easy to handle anymore. Am I doing something wrong?
