### ISSUE TITLE
Kubeseal to use cobra library

### ISSUE THREAD

**Issue by juan131** [bitnami-labs/sealed-secrets#717]
**Which component**:

- kubeseal

**Is your feature request related to a problem? Please describe.**

The current CLI, kubeseal, is quite complex since every action this CLI can perform depends on a series of flags. In other words, there are no subcommands to help simplifying the CLI usage for certain use cases.

You can simply run the command below to realize there are **47 supported flags**!! 

```console
$ kubeseal --help
Usage of kubeseal:
(...)
```

This result in a poor UX that makes it quite difficult to new potential users to adopt the project.

**Describe the solution you'd like**

Use [cobra library](https://github.com/spf13/cobra) to split the current supported use cases on several subcommands. For instance:

- `kubeseal fetch` in replacement of `--fetch-cert` flag.
- `kubeseal merge` in replacement of `--merge-into` flag.
- `kubeseal re-encrypt` in replacement of `--re-encrypt` flag.
- `kubeseal recovery` in replacement of `--recovery-unseal` flag.
- `kubeseal raw` in replacement of `--raw` flag.
- `kubeseal validate` in replacement of `--validate` flag.

Cobra also makes it very simple to create/manage a local config file for kubeseal (`~/.kubesea/config`) and create a `kubeseal config` subcommand to allow users to configure locally settings such as the controller name and the controller namespace. This can also help to reduce the number of required flags to use the CLI.

**Describe alternatives you've considered**

N/A

**Additional context**

Adopting the cobra interface is an important code refactoring that will require adapting all the docs and it'll require bumping the new major version. That said, we should prioritize not introducing incompatibilities in the controller side with kubeseal `0.x` series.

**Comment by mkmik** [comment]
A lot of people would love to overhaul the CLI but also a lot of people depend on the existing CLI in automation.

I believe strongly in backward compatibility and I think the success of this project was due in no small part to our ability to not break things for years. Most users if the sealed secrets project are 'casual users', namely users that interact with the tool only once in a while, some even years apart. 

A new UX ideally should be offered via a new command or a new entry point to the kubeseal command.

**Comment by juan131** [comment]
Thanks @mkmik ! I totally agree with you: backwards compatibility is one of keys that made this project successful and we should put all our efforts on avoiding introducing breaking changes.

That said, I'm not talking about introducing major changes in the controller side, which should be compatible with both `0.x` and the future `1.x` series, but exclusively the CLI.

Users that make use of kubeseal in their automations should't be affected if they were cautious. Let's say some users use a simple GH action such as the one below:

```yaml
jobs:
  sealed-secret:
    name: Sealed Secret
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Setup kubeseal
      run: |
        version="$(curl -sfL https://api.github.com/repos/bitnami-labs/sealed-secrets/releases | jq -r .[].tag_name | grep -v helm | head -n 1)"
        curl -sfLO https://github.com/bitnami-labs/sealed-secrets/releases/download/v${version}/kubeseal-${version}-linux-amd64.tar.gz
        tar xfz kubeseal-${version}-linux-amd64.tar.gz
        mv kubecfg /usr/local/bin/kubecfg && chmod +x /usr/local/bin/kubecfg
    - name: Run kubeseal
      run: |
        kubeseal --flagA --flagB --flagC ...
```

They could be affected because **they don't have any control at all of the kubeseal version they're using, which is an anti-pattern.** However, sticking to `0.x` series would be as simple as applying this change (dummy example):

```diff
- version="$(curl -sfL https://api.github.com/repos/bitnami-labs/sealed-secrets/releases | jq -r .[].tag_name | grep -v helm | head -n 1)"
+ version="$(curl -sfL https://api.github.com/repos/bitnami-labs/sealed-secrets/releases | jq -r .[].tag_name | grep -v helm | grep 'v0.' | head -n 1)"
```

So yes.. It could break things in their automations, but only if they are careless about the version they're installing (including upgrading to a new major version without noticing).
