### ISSUE TITLE
Add/restore openapi schema for CRD

### ISSUE THREAD

**Issue by anguslees** [bitnami-labs/sealed-secrets#82]
See discussion during PR #73.  We had to remove the schema due to upstream k8s limitations that left us with no option to keep the schema _and_ allow an object with arbitrary keys.  This issue is to track finding a workaround and/or upstream fix that allows us to have key/value objects _and_ a CRD schema.

**Comment by smoyer64** [comment]
#152 was closed as a duplicate of this issue.  That's not exactly true as that issue was specific to having validation specified in a schema.

**Comment by mkmik** [comment]
Currently we have a dummy schema in the `schema-v1alpha1.yaml` file:

```
openAPIV3Schema:
  type: object
  properties:
    spec:
      type: object
      x-kubernetes-preserve-unknown-fields: true
    status:
      x-kubernetes-preserve-unknown-fields: true
```

It's shared by the jsonnet and the helm templates.
