### ISSUE TITLE
`type` property is removed between SealedSecret and Secret

### ISSUE THREAD

**Issue by piontec** [bitnami-labs/sealed-secrets#87]
I have a SealedSecret like this
```
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ceph-admin
  namespace: ns
  labels:
    component: ceph-secrets
type:
  kubernetes.io/rbd
spec:
  encryptedData:
    key: 1234
```

But the `type: kubernetes.io/rbd` argument is not passed forward to the `Secret` object
