### ISSUE TITLE
issue when encrypting with kubeseal 0.18.0

### ISSUE THREAD

**Issue by phlukman** [bitnami-labs/sealed-secrets#879]
**Which component*

kubeseal version 0.18.0
sealed-secrets  Chart version 2.3.0

**Describe the bug**
Unable to run kubeseal command to encrypt the secret file and a Go error is launched with below message.

panic: attempted to parse unknown event: none [recovered]
        panic: attempted to parse unknown event: none

kubeseal  --controller-name=sealed-secrets --controller-namespace=kube-system <secret.yaml >sealed-secret.yaml

**To Reproduce**
1. Install Helm release 
helm install sealed-secrets sealed-secrets/sealed-secrets -n kube-system --debug  

2.Install kubeseal 
brew install kubeseal

3. Encrypt secret
kubeseal  --controller-name=sealed-secrets --controller-namespace=kube-system  -o yaml <secret.yaml >sealed-secret.yaml

1. Install Helm release 
helm install sealed-secrets sealed-secrets/sealed-secrets -n kube-system --debug  

2.Install kubeseal 
brew install kubeseal

3. The content of the secret:
```
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "full.name" . }}
  labels:
  {{- include "labels" . | nindent 4 }}
type: Opaque
stringData:
  my.config.json: |
    {
      "data": {
        "conn": {
          "field1": "value1",
          "field2": "value2",
        }
      }
    }

```

4. Encrypt secret
kubeseal  --controller-name=sealed-secrets --controller-namespace=kube-system  -o yaml <secret.yaml >sealed-secret.yaml

5. See error
```
panic: attempted to parse unknown event: none [recovered]
        panic: attempted to parse unknown event: none

goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc00045f998)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v2@v2.4.0/yaml.go:249 +0x6d
panic({0x1e3eea0, 0xc0000995a0})
        /usr/local/Cellar/go/1.18.3/libexec/src/runtime/panic.go:838 +0x207
gopkg.in/yaml%2ev2.(*parser).parse(0xc0005fe000)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v2@v2.4.0/decode.go:158 +0x154
gopkg.in/yaml%2ev2.(*Decoder).Decode(0xc00045fa08, {0x1e012e0?, 0x2b8a588})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/gopkg.in/yaml.v2@v2.4.0/yaml.go:122 +0x107
github.com/bitnami-labs/sealed-secrets/pkg/multidocyaml.isMultiDocumentYAML({0xc0005c2400, 0x1cc, 0x200})
        /private/tmp/kubeseal-20220602-72017-lkgeub/pkg/multidocyaml/multidocyaml.go:14 +0x205
github.com/bitnami-labs/sealed-secrets/pkg/multidocyaml.EnsureNotMultiDoc({0xc0005c2400?, 0xc000010010?, 0xc0000d6be0?})
        /private/tmp/kubeseal-20220602-72017-lkgeub/pkg/multidocyaml/multidocyaml.go:19 +0x1e
main.readSecret({0x85ce758, 0xc0000d6be0}, {0x21fd1a0?, 0xc000010010?})
        /private/tmp/kubeseal-20220602-72017-lkgeub/cmd/kubeseal/main.go:146 +0x5d
main.seal({0x21fd1a0, 0xc000010010}, {0x21fd1c0, 0xc000010018}, {0xc0001fe150, {0x21fcb00, 0xc00000e9d8}, {0xc0001e0c40, 0x3, 0x4}, ...}, ...)
        /private/tmp/kubeseal-20220602-72017-lkgeub/cmd/kubeseal/main.go:262 +0x109
main.run({0x220ebe8, 0xc0000440c0}, {0x21fd1c0?, 0xc000010018}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...)
        /private/tmp/kubeseal-20220602-72017-lkgeub/cmd/kubeseal/main.go:766 +0xc4e
main.main()
        /private/tmp/kubeseal-20220602-72017-lkgeub/cmd/kubeseal/main.go:773 +0x33b

```

**Expected behavior**

I expect to see a secret-sealed.yaml file

**Version of Kubernetes**:
1.21

- Output of `kubectl version`:

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:17:11Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.20-eks-154371", GitCommit:"1543713dd4762c0a4f87b7af825b0e5c2ece7873", GitTreeState:"clean", BuildDate:"2022-02-16T20:59:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.24) and server (1.18) exceeds the supported minor version skew of +/-1

```

**Comment by mkmik** [comment]
The error message is very bad indeed.

You can't pass a template as input of sealed-secrets

**Comment by mkmik** [comment]
What you want to do is this:

1. Create an untemplated secret:

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: dummy
type: Opaque
stringData:
  my.config.json: |
    {
      "data": {
        "conn": {
          "field1": "value1",
          "field2": "value2",
        }
      }
    }
```

2 seal it with the `namespace-wide` scope so that you can choose the name at deployment time.

```console
$ kubeseal --controller-name=sealed-secrets --controller-namespace=kube-system -o yaml --scope namespace-wide <secret.yaml >sealed-secret.yaml
```

3. Edit the resulting "sealed" yaml file and put the helm template bits in it:

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: dummy
  namespace: default
spec:
  encryptedData:
    my.config.json: AgAUyzYX3fZpt4ngMtQR4PbuiRAfmFDo5eyt8hcmiQBURkdy4v5/B1cJnv1LzAP0rML/dtA60chgmQfm2WpdrBKynV1nSIkOGfRPYtJ/K9YlKPu49xvocW3ZF7cDwgmMGBSl4XAyzDtCHQzzPP8j2tNawoQQaA99jd7c4DnS3hSx4krQ3G336hEwkO36JQzu7MrtZxlCwSnMKTMLPs5BM4PZzOK0T134Aw9FB4q7UjDY3Nn9O7c8SwvSlvVFDGPCa9jsn5x1JDfztasYCFvretn5NvPZx/2lc5t5IGSqPEumXuQU8swlxyJJYAiZa8woPtW6q3ltUdaDGOKK41MGf18edCownhkqJo8FIIQv5Yut9WundOIbSQrqHBt86ECttSty2CM6tIEIHE9mYMvApdewMmJaSatSt5+fF4W4sbZlaa5zJhQb5VDzhi1rADt94AJLTr62+9VEVjDENawl+1oz07CH7TCrRQwJVITAV9AEYyQ4PQwEN1mOR3Eg22B3kh8Tgn4hUJVgb2e9X+MZDnlJmD481Ez37BbjR1GJzTRPDg8J4lkjrAMpgGTEgVxW/FA8lR17OeV07FZ5kgGxNLRNJergPwXoeASdBD6T6aRAskx9IYclL0x45iE6gqOlXOO3tj4bUS2b6ibXy81sYfrcKizG16UkeMLqf/CWsADo9zS7hcux6qaEEP/d8ba79S3n1Kufd2BNRK7kKYtPbKbi2RQaVkSZVZfb8WoAjxL9VMPBVsGWjm0vDmrT1EujXmzXRZZs5fD9toxwUnbBonzAROnJfAjA3CZ6x5zawVuy6mq/UPCKuRVH+aJ4
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: dummy
      namespace: default
    type: Opaque
```

-->

```yaml
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: {{ template "full.name" . }}
  namespace: default
spec:
  encryptedData:
    my.config.json: AgAUyzYX3fZpt4ngMtQR4PbuiRAfmFDo5eyt8hcmiQBURkdy4v5/B1cJnv1LzAP0rML/dtA60chgmQfm2WpdrBKynV1nSIkOGfRPYtJ/K9YlKPu49xvocW3ZF7cDwgmMGBSl4XAyzDtCHQzzPP8j2tNawoQQaA99jd7c4DnS3hSx4krQ3G336hEwkO36JQzu7MrtZxlCwSnMKTMLPs5BM4PZzOK0T134Aw9FB4q7UjDY3Nn9O7c8SwvSlvVFDGPCa9jsn5x1JDfztasYCFvretn5NvPZx/2lc5t5IGSqPEumXuQU8swlxyJJYAiZa8woPtW6q3ltUdaDGOKK41MGf18edCownhkqJo8FIIQv5Yut9WundOIbSQrqHBt86ECttSty2CM6tIEIHE9mYMvApdewMmJaSatSt5+fF4W4sbZlaa5zJhQb5VDzhi1rADt94AJLTr62+9VEVjDENawl+1oz07CH7TCrRQwJVITAV9AEYyQ4PQwEN1mOR3Eg22B3kh8Tgn4hUJVgb2e9X+MZDnlJmD481Ez37BbjR1GJzTRPDg8J4lkjrAMpgGTEgVxW/FA8lR17OeV07FZ5kgGxNLRNJergPwXoeASdBD6T6aRAskx9IYclL0x45iE6gqOlXOO3tj4bUS2b6ibXy81sYfrcKizG16UkeMLqf/CWsADo9zS7hcux6qaEEP/d8ba79S3n1Kufd2BNRK7kKYtPbKbi2RQaVkSZVZfb8WoAjxL9VMPBVsGWjm0vDmrT1EujXmzXRZZs5fD9toxwUnbBonzAROnJfAjA3CZ6x5zawVuy6mq/UPCKuRVH+aJ4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      labels:
        {{- include "labels" . | nindent 6 }}
      creationTimestamp: null
      name: {{ template "full.name" . }}
      namespace: default
    type: Opaque
```


4. when you want to change the contents of your secret pass the new  `kubeseal --raw ...`  and update the base64 blob in your sealed-secre.yaml template.




Please read https://github.com/bitnami-labs/sealed-secrets#scopes for more information about scopes

And about the `--raw` mode: https://github.com/bitnami-labs/sealed-secrets#raw-mode-experimental
