### ISSUE TITLE
Service Annotations in service.yaml

### ISSUE THREAD

**Issue by iamhoges** [bitnami-labs/sealed-secrets#942]
Helm Chart version 2.6.1 service manifest file only accepts commonAnnotations.

```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sealed-secrets.fullname" . }}
  namespace: {{ include "sealed-secrets.namespace" . }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
```

The service.annotations in the `values.yaml` file serves no purpose.
```
service:
...
  annotations: {}
```
